# Exploration of Data and Cleaning steps

Importing our claims dataset and reading the excel file into claim_df dataframe

In [1]:
from google.colab import drive
drive.mount('/content/drive')

# Import the Pandas library
import pandas as pd

# Assigning the claim data path
claim_data_path = "/content/drive/My Drive/SBD_CAPSTONE/Raw_Data/Claims_Data.xlsx"


# Load the file using read_excel since it's a Excel file
claim_df = pd.read_excel(claim_data_path)

# Display the first few rows of the dataframe
print(claim_df.head())

Mounted at /content/drive
   Claim Number  Claim Number Form Model Number  \
0      20028686            2659466  13C226JD333
1      20032406            2797315  11AEE1L4333
2      20032941            2810434  13A276WF333
3      30843126            2904575  41BS2BVG799
4      20033818            2849132  53AWEFJA330

        Warranty Item Description Serial Number     Engine Model  \
0  MOWER:MINI LT:30SD 6SPD J STYL   1K045B20348  752Z4P90JUD
1           MOWER:159CC ENG 18 IN   1B125P10128  752L2P65WT
2     MOWER:LT5:38SD 6SPD W STYLE   1F018B40253  752Z4P90HUD
3   316.791770:27CC:MPP:BV:149:14   1F097DF1822  -
4    MOWER:PZFS:54FAB HYD J STYLE   1F237H30036              NaN

          Engine Serial Transmission Model Transmission Serial  \
0  4P90JUD1502111B0052     618-05056B          1H255Q11381
1  2P65WT 1501221A0083                 NaN                 NaN
2  1803143A0170            618-04914A          0E018Q110519
3  -                                   NaN                 NaN
4  4715211413              618-07112A          7095D50230

  Repair Dealer Number  ... Owner State   Owner Zip        Purchase Date  \
0               S40899  ...          QL  4700        2016-09-22 00:00:00
1               S41744  ...          NS  2171        2019-01-16 00:00:00
2               S40655  ...          QL  4124        2018-12-29 00:00:00
3               S03730  ...          MN  55127       2018-05-08 00:00:00
4               S43090  ...          VI  3820        2017-10-13 00:00:00

          Failure Date          Repair Date Hours Used  \
0  2018-01-03 00:00:00  2018-01-09 00:00:00       20.0
1  2019-01-16 00:00:00  2019-01-17 00:00:00        0.0
2  2019-03-15 00:00:00  2019-03-15 00:00:00       11.0
3  2019-10-08 00:00:00  2019-11-06 00:00:00        5.0
4  2019-06-12 00:00:00  2019-06-21 00:00:00       45.0

   Check Calendar Month Name Abbr Posted Calendar Month Name Abbr  \
0                        Apr/2020                        Apr/2020
1                        Feb/2020                        Feb/2020
2                        Nov/2019                        Nov/2019
3                        Nov/2019                        Nov/2019
4                        Nov/2019                        Nov/2019

  Deliver Cost  Total Claim Dollars
0          0.0               218.98
1          0.0                73.96
2          0.0                75.75
3          0.0                34.20
4          0.0               777.79

[5 rows x 21 columns]

In [2]:
# Importing and reading our Failure data

failure_part_data_path = "/content/drive/My Drive/SBD_CAPSTONE/Raw_Data/Failure_Part_Data.xlsx"
failure_part_df = pd.read_excel(failure_part_data_path)
print(failure_part_df.head())

   Failure Part id   Claim Number             Failure Description  \
0                 1      20028686  Loose
1                 2      20032406  Damaged at Factory
2                 3      20032941  Will not Charge
3                 4      30843126  Cracked
4                 5      20033818  Incorrect Part

  Failure Part        Failure Part Description  \
0   757-04083A   SEAT:3400:MED BACK:BLK NO OPS
1    925-04347                SW:KEY:MOMENTARY
2    925-1707D  BAT:U1:300 CCA DRY VENTED T UD
3    753-06687             SHBLK:FC27CC:SC BLO
4    951-12725  CAP:FUEL:3.50" ONEWAY VENT FKM

                                 Complaint Diagnosis  \
0                      guide inserts broken off seat
1    TRACE FAULT, DEFECTIVE IGNITION SWITCH, REPL...
2                                    Faulty battery.
3    Found engine has a broken connecting rod. co...
4                                    Fuel Cap recall

                                      Work Performed  Vendor Number
0    removed seat due to its sliding when custome...        10403.0
1    TRY TO KEY START UNIT WOULDNT TURN OVER, TRA...       547628.0
2    Charged battery, tested faulty at 108CCA. Te...       725200.0
3                   Cylinder/Piston Service (2cycle)            0.0
4    Replaced fuel caps to breathe correctly as p...       547628.0

In [4]:
# Importing and reading our replacement part data

replacement_part_data = "/content/drive/My Drive/SBD_CAPSTONE/Raw_Data/Replacement_Part_Data.xlsx"
replacement_part_df = pd.read_excel(replacement_part_data)
print(replacement_part_df.head())

   Claim Number  Replacement Part id Replacement Part  \
0      20028686                    1       757-04083A
1      20032406                    2        925-04347
2      20032941                    3        925-1707D
3      30843126                    4        753-06687
4      20033818                    5        951-12725

     Replacement Part Description  Part Quantity  Part Price  \
0   SEAT:3400:MED BACK:BLK NO OPS              1      169.07
1                SW:KEY:MOMENTARY              1       22.24
2  BAT:U1:300 CCA DRY VENTED T UD              1       49.06
3             SHBLK:FC27CC:SC BLO              1        0.00
4  CAP:FUEL:3.50" ONEWAY VENT FKM              2       51.59

   Part Extended Price  Labor Rate  Paid Labor Hours  Total Failure Cost
0               169.07          60              0.50               199.07
1                22.24          60              0.75                67.24
2                49.06          60              0.33                68.86
3                 0.00          76              0.25                19.00
4               103.18          60              0.25               118.18

In [5]:
# Check the info for claims data

claim_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375364 entries, 0 to 375363
Data columns (total 21 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Claim Number                     375364 non-null  int64
 1   Claim Number Form                375364 non-null  int64
 2   Model Number                     375364 non-null  object
 3   Warranty Item Description        375364 non-null  object
 4   Serial Number                    375364 non-null  object
 5   Engine Model                     334913 non-null  object
 6   Engine Serial                    335070 non-null  object
 7   Transmission Model               279326 non-null  object
 8   Transmission Serial              279406 non-null  object
 9   Repair Dealer Number             375364 non-null  object
 10  Owner City                       305478 non-null  object
 11  Owner State                      305381 non-null  object
 12  Owner Zip                        305481 non-null  object
 13  Purchase Date                    375364 non-null  object
 14  Failure Date                     375364 non-null  object
 15  Repair Date                      375364 non-null  object
 16  Hours Used                       375364 non-null  float64
 17  Check Calendar Month Name Abbr   375364 non-null  object
 18  Posted Calendar Month Name Abbr  375364 non-null  object
 19  Deliver Cost                     375364 non-null  float64
 20  Total Claim Dollars              375364 non-null  float64
dtypes: float64(3), int64(2), object(16)
memory usage: 60.1+ MB

## Claim Dataset

### Claim Number

In [7]:
# Unique number of claims in dataset

total_claims = claim_df['Claim Number'].nunique()
print(f"Total number of claims: {total_claims}")

# Missing values in claim Number

missing_claims = claim_df['Claim Number'].isnull().sum()
print(f"Number of missing claim numbers: {missing_claims}")

# Print the current data type and see if it's correct
print(f"Claim Number data type: {claim_df['Claim Number'].dtype}") # It is correctly classified as integer

Total number of claims: 375364
Number of missing claim numbers: 0
Claim Number data type: int64

### Claim Number Form - Dropping this Column

In [8]:
# Claim number form - Total number of claims

print(f"Total number of unique values in Claim Number Form :{claim_df['Claim Number Form'].nunique()}")

# We already have a unique identifier Claim Number in our data, so we don't need this Claim Number Form
# So, we will be dropping this column

claim_df = claim_df.drop(columns=['Claim Number Form'])

Total number of unique values in Claim Number Form :373265

### Model Number

In [ ]:
# Model Number - Total number of unique Model numbers

print(f"Total number of unique values in Model Number :{claim_df['Model Number'].nunique()}")

# Number of missing values in Model Number
missing_model_number = claim_df['Model Number'].isnull().sum()
print(f"Number of missing values in Model Number: {missing_model_number}")

# Check the data type of Model Number
print(f"Model Number data type: {claim_df['Model Number'].dtype}") # It is correctly classified as object

Total number of unique values in Model Number :3916
Number of missing values in Model Number: 0
Model Number data type: object

In [18]:
# Filter 'Model Number' for values less than 7 characters in length

model_numbers_less_than_7 = claim_df[claim_df['Model Number'].str.len() < 7]['Model Number']
model_numbers_less_than_7

540       123456
598       123456
1102      123456
2226      123456
221302    123456
221317    123456
221567    123456
221940    123456
285993     11111
288846     12345
289385    123456
289465    123456
290081    123456
290196    123456
291012    123456
345417     11111
Name: Model Number, dtype: object

In [19]:
# Importing the numpy library

import numpy as np

# When we have looked our dataset we have found 16 model numbers which seemed incorrect with model numbers as 123456,12345,111111

model_number_to_replace = ['123456','12345','11111']
claim_df['Model Number'] = claim_df['Model Number'].replace(model_number_to_replace, np.nan)

In [20]:
# updated unique and missing value count

print(f"After replacing -  Total number of unique values in Model Number :{claim_df['Model Number'].nunique()}")
missing_model_number = claim_df['Model Number'].isnull().sum()
print(f"Updated Number of missing values in Model Number: {missing_model_number}")

After replacing -  Total number of unique values in Model Number :3913
Updated Number of missing values in Model Number: 16

### Warranty Item Description

In [21]:
# Warranty Item Description

# Number of unique values in warranty item description
print(f"Total number of unique values in Warranty Description :{claim_df['Warranty Item Description'].nunique()}")

# Missing values in Warranty Item Description
missing_warranty_description = claim_df['Warranty Item Description'].isnull().sum()
print(f"Number of missing values in Warranty Item Description: {missing_warranty_description}")

# Check the data type of the Warranty Item Description
print(f"Warranty Item Description data type: {claim_df['Warranty Item Description'].dtype}") # Since, it is a description...it is correctly classified as object

Total number of unique values in Warranty Description :2122
Number of missing values in Warranty Item Description: 0
Warranty Item Description data type: object

### Serial Number

In [22]:
# Serial Number

print(f"Total number of unique values in Serial Number :{claim_df['Serial Number'].nunique()}")

# Serial Number is generally unique value for each of the Machine

# We can see that the number of unqiue values in serial is not equal to number of claim numbers which means that
# some machines have failed more than once and came for repair multiple times

# Check for missing values in Serial Number

missing_serial_number = claim_df['Serial Number'].isnull().sum()
print(f"Number of missing values in Serial Number: {missing_serial_number}")

Total number of unique values in Serial Number :304385
Number of missing values in Serial Number: 0

In [31]:
# Filter 'Model Number' for values less than 8 characters in length i want to see only unique numbers

unique_model_numbers = claim_df[claim_df['Serial Number'].str.len() < 8]['Serial Number'].unique()
unique_model_numbers

array(['123456', 'XX0000', '0000', 'XX28', 'XX', '1C484', '00000',
       '12356', '027721', '1234567', '0000000', '000000', '2222', '28',
       '555555'], dtype=object)

In [ ]:
# Though data shows there are no missing values, when we looked at the serial number data we can see that the data has
# lot of errors and needs to be corrected

# There are lot of rows with serial number as 0000, 00000, XXXXX, 123456 and so on
# These should be classified as missing values

import pandas as pd
import numpy as np

# List of serial numbers to be replaced with NaN
serials_to_replace = [
    "0000", "00000", "000000", "0000000", "000000000", "00000000000",
    "11110000", "11111111100", "1111111111", "11111111110", "11111111111",
    "123456", "1234567", "12356", "NONE0000", "NOSERIAL", "NOTAVA0000",
    "XX", "XX0000", "XX28", "XXXXXKX0000", "XXXXXS30305", "XXXXXXX0000", "XXXXXXXXXXX"
]

# Replace specified serial numbers with NaN
claim_df['Serial Number'] = claim_df['Serial Number'].replace(serials_to_replace, np.nan)

# Check the operation
print(claim_df['Serial Number'].head())

# Check for missing values again
missing_serial_number = claim_df['Serial Number'].isnull().sum()
print(f"Number of missing values in Serial Number: {missing_serial_number}")

0    1K045B20348
1    1B125P10128
2    1F018B40253
3    1F097DF1822
4    1F237H30036
Name: Serial Number, dtype: object
Number of missing values in Serial Number: 1331

### Engine Model

In [32]:
# Print unique values
print(f"Total number of unique values in Engine Model :{claim_df['Engine Model'].nunique()}")

# Check for missing values count
missing_engine_model = claim_df['Engine Model'].isnull().sum()
print(f"Number of missing values in Engine Model: {missing_engine_model}")

# Check for data type
print(f"Engine Model data type: {claim_df['Engine Model'].dtype}")

Total number of unique values in Engine Model :2563
Number of missing values in Engine Model: 40451
Engine Model data type: object

In [33]:
import pandas as pd

# There are lot of spaces for Engine model Column in our data so, we stripped spaces from 'Engine Model'
claim_df['Engine Model'] = claim_df['Engine Model'].str.strip()

In [34]:
# Handling incorrect data in Engine Model

import pandas as pd
import numpy as np

# list of patterns to replace with NaN
patterns_to_replace = [
    '0', '00', '000', '0000', '00000', '000000', '0000000', '00000000',
    '000000000', '0000000000', '00000000000', '000000000000', '0000000000000',
    '00000000000000', '000000000000000', 'XXXXXXXXXX', 'XXXXXXXXXXXX',
    'XXXXXXXXXXX', 'XXXXXXXXXXXXXX', 'XXXXXXXXXXXXX', 'XXXXX', 'XXXXXX',
    'XXXXXXX', 'XXXXXXXX', 'XXXXXXXXX', 'XXXXXXXXXX', 'XXXXXXXXXXX',
    'XXXXXXXXXXXX', 'XXXXXXXXXXXXX', 'XXXXXXXXXXXXXX', 'XXXXXXXXXXXXXXX',
    '1', '11', '111', '1111', '11111', '111111', '1111111', '11111111',
    '111111111', '1111111111', '11111111111', '111111111111', '1111111111111',
    '11111111111111', '111111111111111', '123', '1234', '12345', '123456',
    '1234567', '12345678', '123456789', '1234567890', '01010', '010100',
    '010101', '0101010', '010101010', '0123','-','XZXXXX','UNKNOWN','1XXXXXXXXX',
    '1XXXXXXX','XX','X','NO TAG','XXXX','99999','NA','N/A'
]

# Replace the values in the DataFrame
claim_df['Engine Model'] = claim_df['Engine Model'].replace(patterns_to_replace, np.nan)

# Check the unique values after replacement to ensure no unexpected patterns remain
print(claim_df['Engine Model'].nunique())

# check missing value sum again
missing_engine_model = claim_df['Engine Model'].isnull().sum()
print(f"Updated Number of missing values in Engine Model: {missing_engine_model}")

2503
Updated Number of missing values in Engine Model: 42140

### Engine Serial - Dropping the column

In [ ]:
# Print unique values
print(f"Total number of unique values in Engine Serial :{claim_df['Engine Serial'].nunique()}")

# Print Missing value count
missing_engine_serial = claim_df['Engine Serial'].isnull().sum()
print(f"Number of missing values in Engine Serial: {missing_engine_serial}")

# Data type of missing value
print(f"Engine Serial data type: {claim_df['Engine Serial'].dtype}")

Total number of unique values in Engine Serial :270153
Number of missing values in Engine Serial: 40294
Engine Serial data type: object

The Engine Serial Column has a high unique values more than 73% and also 11% of missing values and this number would be even higher if we convert rubbish data like 1111, 1234,123456 etc as missing values. Hence, this column is not useful for our project, so we are dropping this column.

In [ ]:
claim_df.drop(columns=['Engine Serial'], inplace=True)

### Transmission Model

In [35]:
# Print Unique values
print(f"Total number of unique values in Transmission Model :{claim_df['Transmission Model'].nunique()}")

# Print Missing values
missing_transmission_model = claim_df['Transmission Model'].isnull().sum()
print(f"Number of missing values in Transmission Model: {missing_transmission_model}")

# Check the data type
print(f"Transmission Model data type: {claim_df['Transmission Model'].dtype}")

Total number of unique values in Transmission Model :1530
Number of missing values in Transmission Model: 96038
Transmission Model data type: object

In [ ]:
import pandas as pd

# there are lot of spaces for values in our data so, we need to Strip spaces from 'Transmission Model'
claim_df['Transmission Model'] = claim_df['Transmission Model'].str.strip()

In [36]:
# List of values to replace with NaN in the 'Transmission Model' column
values_to_replace = [
    "XXXXXXXXXXX", "N/A", "XXXXXXX", "XXXXXXXX", "XXXXXXXXX", "XXXXXX", "00000003",
    "000000000000000", "000000000000", "000000000", "0000000000000", "00000000000",
    "00000000000000", "0000000000", "00000", "000000", "0000000", "0000", "01010",
    "010101", "0101010", "010101010", "0123", "1", "111", "1111111111", "11111111111",
    "1234", "XXX", "12345", "XXXXX", "NA", "NONE", "X", "111111111111", "123456",
    "UNREADBLE", "UNREADABLE", "111", "0101010", "-", "XXXXXXXXXXXXXXX", "UNKNOWN",
    "1234567", "XXXX", "NO LONGER VISIB", "BLANK TAG", "00000000", "NOTAG", "11111111",
    "12", "XXXXXXXXXX", "000", "ZZZZZZ", "999999", "222", "0", "1", "1111XXXX", "0001234",
    "UNABLE TO READ", "ZZZZZZZ", "00", "23", "1111", "1111111", "999999999999999", "VISION",
    "AAAAA", "123-456", "1234ABC", "99999", "111111111111111", "XX", "111111", "123456789",
    "NOTAVAILABLE", "111111111", "0101001", "010101010", "XXX-XXXX", "TAG GONE", "CAN NOT LOCATE",
    "999-9", "000001", "NNNN", "1111-111", "N", "NO NUMBER", "NA123", "NOT AVALIABLE",
    "XXXXXXXXXXXX", "N / A", "NNNNN", "NLA", "NA0001000", "1111111111111", "999999999", "ZZZZZZZZ",
    "123", "RUBBED OFF", "AAAAAAAAAAAAAAA", "NNNNNNNN", "NOTRANSMISSION", "22222222", "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXX", "XOXOXO", "UNKOWN", "NONE KNOWN", "99999999", "NO TRANS", "11111111111111",
    "NSN", "1112", "NOT APPLICABLE", "NO TRANSMISSION", "123456PP", "0000-000", "01", "2222222",
    "01111", "0000-0000", "111XXX11111", "111333XXX", "TAGGONE", "NANANAN", "NONUMBER", "MISSING",
    "CANT READ IT", "0X0X0X", "THERE IS NO", "N/N", "NOT AVAILABLE", "0100000", "XX12", "XXC",
    "1234NAHHH", "XXX111", "113XXXXX", "123455", "9999-9999999999", "1234563", "X1111111", "11",
    "11111-111", "00000000012", "000001234", "9999999", "22222", "2225", "0"
]

# Import necessary libraries
import pandas as pd
import numpy as np

# Replace the values in the DataFrame
claim_df['Transmission Model'] = claim_df['Transmission Model'].replace(values_to_replace, np.nan)

# check number of unique values again
print(f"Updated Total number of unique values in Transmission Model :{claim_df['Transmission Model'].nunique()}")

# check updated number of missing values
missing_transmission_model = claim_df['Transmission Model'].isnull().sum()
print(f"Updated Number of missing values in Transmission Model: {missing_transmission_model}")

Updated Total number of unique values in Transmission Model :1522
Updated Number of missing values in Transmission Model: 96222

### Transmission Serial - Dropping the column

In [ ]:
# Print unique values
print(f"Total number of unique values in Transmission Serial :{claim_df['Transmission Serial'].nunique()}")

# Check for missing value count
missing_transmission_serial = claim_df['Transmission Serial'].isnull().sum()
print(f"Number of missing values in Transmission Serial: {missing_transmission_serial}")

# Check for the data type
print(f"Transmission Serial data type: {claim_df['Transmission Serial'].dtype}")

# We can drop this column as there are a lot of unqiue values in this data

Total number of unique values in Transmission Serial :214151
Number of missing values in Transmission Serial: 95958
Transmission Serial data type: object

There are lot of unique values and missing values are present in our Tranmission serial column. Also, this data is not much useful for us, hence, we are dropping this column.

In [ ]:
claim_df.drop(columns=['Transmission Serial'], inplace=True)

### Repair Dealer Number

In [ ]:
# Check for unique values
print(f"Total number of unique values in Repair Dealer Number :{claim_df['Repair Dealer Number'].nunique()}")

# Check for missing values
missing_repair_dealer_number = claim_df['Repair Dealer Number'].isnull().sum()
print(f"Number of missing values in Repair Dealer Number: {missing_repair_dealer_number}")

# Check data type
print(f"Repair Dealer Number data type: {claim_df['Repair Dealer Number'].dtype}")

Total number of unique values in Repair Dealer Number :5660
Number of missing values in Repair Dealer Number: 0
Repair Dealer Number data type: object

In [37]:
# Though it is showing there are no missing values for Repair Dealer number, when we closely look at the data there are a lot of rows with Dealer number as Unknown
# We need to convert these rows to missing values

import pandas as pd
import numpy as np

# Replace 'Unknown' with NaN in the Repair Dealer Number column
claim_df['Repair Dealer Number'] = claim_df['Repair Dealer Number'].replace('Unknown', np.nan)

# Check how many NaNs are present in the column to confirm the change
missing_count = claim_df['Repair Dealer Number'].isna().sum()
print(f"Number of missing values in Repair Dealer Number after replacement: {missing_count}")

Number of missing values in Repair Dealer Number after replacement: 6728

### Owner City

In [ ]:
# Print unique values
print(f"Total number of unique values in Owner City :{claim_df['Owner City'].nunique()}")

# Check for missing values
missing_owner_city = claim_df['Owner City'].isnull().sum()
print(f"Number of missing values in Owner City: {missing_owner_city}")

# Check the data type
print(f"Owner City data type: {claim_df['Owner City'].dtype}")

Total number of unique values in Owner City :27373
Number of missing values in Owner City: 69886
Owner City data type: object

In [38]:
# When we checked the data in excel, we can see that around 150 rows have either zip code or street name mentioned in the place of city
# we can see it below in the output

# sort owner city data by ascending and display top 150 rows
sorted_owner_city = claim_df.sort_values(by='Owner City', ascending=True)
sorted_owner_city['Owner City'].head(150)

# print it to list
sorted_owner_city['Owner City'].head(150).tolist()

[',LUCEDALE                ',
 ',LUCEDALE                ',
 '.                        ',
 '.                        ',
 '.                        ',
 '/NEWBURGH                ',
 '00736                    ',
 '02338                    ',
 '08090                    ',
 '0TTER LAKE               ',
 '103 AVENUE               ',
 '1208 DES MUGUETS         ',
 '1211 BONO RD             ',
 '12822                    ',
 '13212                    ',
 '13619                    ',
 '13820                    ',
 '139 N CAIN STREET        ',
 '14075                    ',
 '14655 64TH COURT NORTH   ',
 '14655 64TH COURT NORTH   ',
 '150 MILE                 ',
 '150 MILE HOUSE           ',
 '150 MILE HOUSE           ',
 '15015                    ',
 '15026                    ',
 '15026                    ',
 '15237                    ',
 '17TREACS010              ',
 '1835 CH LECLEREC         ',
 '19 EUSTANE STREET        ',
 '19709                    ',
 '1K230DC2445              ',
 '2000 SUTTON LANE         ',
 '2000 SUTTON LANE         ',
 '2000 SUTTON LANE         ',
 '2016 WINDSONG DR         ',
 '20650                    ',
 '21074                    ',
 '21122                    ',
 '21286                    ',
 '2164086278               ',
 '220 JACK LAKE RD         ',
 '22504                    ',
 '23124                    ',
 '23504                    ',
 '23608                    ',
 '2400 VZCR 1903           ',
 '2474                     ',
 '27370                    ',
 '27591                    ',
 '27597                    ',
 '27616                    ',
 '28716                    ',
 '28716                    ',
 '28773                    ',
 '29229                    ',
 '30650                    ',
 '3208 W. 74 TH LN.        ',
 '340-8191                 ',
 '340-8191                 ',
 '3485 MARKET ST           ',
 '36037                    ',
 '36037                    ',
 '37070                    ',
 '39465                    ',
 '4000                     ',
 '4000                     ',
 '40014                    ',
 '40014                    ',
 '40328                    ',
 '40328                    ',
 '4211                     ',
 '4211                     ',
 '4211                     ',
 '4211                     ',
 '4211                     ',
 '4275 - WITHEREN          ',
 '43076                    ',
 '43076                    ',
 '43076                    ',
 '43076                    ',
 '4341                     ',
 '44023                    ',
 '452011                   ',
 '45371                    ',
 '45371                    ',
 '45414                    ',
 '4605 GARRARD RD          ',
 '47468                    ',
 '49097                    ',
 '53 LAKE LINK CIRCLE      ',
 '53 LAKE LINK CIRCLE      ',
 '53 LAKE LINK CIRCLE      ',
 '53 LAKE LINK CIRCLE      ',
 '53 LAKE LINK CIRCLE      ',
 '53 LAKE LINK CIRCLE      ',
 '53 LAKE LINK CIRCLE      ',
 '53 LAKE LINK CIRCLE      ',
 '53 LAKE LINK CIRCLE      ',
 '53 LAKE LINK CIRCLE      ',
 '53014                    ',
 '53142                    ',
 '54220                    ',
 '5987 SHADBURN FERRY RD   ',
 '5987 SHADBURN FERRY RD   ',
 '63 PROVIDENCE RD         ',
 '63131                    ',
 '65401                    ',
 '65401                    ',
 '65401                    ',
 '65401                    ',
 '655 MAYO KL RD GEN DEL   ',
 '677 BUCK CREEK RD        ',
 '70 HUNTER MILL WAY       ',
 '70 HUNTER MILL WAY       ',
 '7056564611               ',
 '71302                    ',
 '716 GLENECHO ST          ',
 '71665                    ',
 '7212 GOFORTH RD          ',
 '7212 GOFORTH RD          ',
 '7212 GOFORTH RD          ',
 '76028                    ',
 '76905                    ',
 '77879                    ',
 '78616                    ',
 '7900 KICKAPOO RD.        ',
 '7900 KICKAPOO RD.        ',
 '828-242-8928             ',
 '9053723705               ',
 '912, DES LIEVRES         ',
 '912, DES LIEVRES         ',
 '91763                    ',
 '9192 SAINT CLAIR HWY     ',
 '9192 SAINT CLAIR HWY     ',
 '9321 N. YUKON            ',
 '?                        ',
 'A,BURTIS                 ',
 'AARAT                    ',
 'AATCO                    ',
 'AB                       ',
 'AB                       ',
 'ABALINE                  ',
 'ABBEVILLE                ',
 'ABBEVILLE                ',
 'ABBEVILLE                ',
 'ABBEVILLE                ',
 'ABBEVILLE                ',
 'ABBEVILLE                ']

We will be correcting this data using excel as it is easier and faster in excel.

### Owner State

In [39]:
# Print unique values
print(f"Total number of unique values in Owner State :{claim_df['Owner State'].nunique()}")

# Check for missing values
missing_owner_state = claim_df['Owner State'].isnull().sum()
print(f"Number of missing values in Owner State: {missing_owner_state}")

# Check for data type
print(f"Owner State data type: {claim_df['Owner State'].dtype}")

Total number of unique values in Owner State :70
Number of missing values in Owner State: 69983
Owner State data type: object

### Owner Zip

In [ ]:
# Print unique values
print(f"Total number of unique values in Owner Zip :{claim_df['Owner Zip'].nunique()}")

# Print misisng value counts
missing_owner_zip = claim_df['Owner Zip'].isnull().sum()
print(f"Number of missing values in Owner Zip: {missing_owner_zip}")

# Print data type
print(f"Owner Zip data type: {claim_df['Owner Zip'].dtype}")

Total number of unique values in Owner Zip :44519
Number of missing values in Owner Zip: 69883
Owner Zip data type: object

### Purchase Date

In [ ]:
# Check missing values
missing_purchase_date = claim_df['Purchase Date'].isnull().sum()
print(f"Number of missing values in Purchase Date: {missing_purchase_date}")

# Check for the data type
print(f"Purchase Date data type: {claim_df['Purchase Date'].dtype}")

Number of missing values in Purchase Date: 0
Purchase Date data type: object

In [41]:
# It is incorrectly clasisfied as object, we need to convert to date format
# Also we won't be needing time for analysis, so we will convert to date only instead of datetime
# When we tried to convert, we got an error OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 9998-12-31 00:00:00,
# at position 129, it means that our data has values with years like 9998 which are not valid

# Pandas datetime format only supports dates within the range 1677-09-21 to 2262-04-11.
# Check for the purchase date column to find the invalid dates

import pandas as pd

# Check the unique years in the column
claim_df['Purchase Date'] = claim_df['Purchase Date'].astype(str)  # Ensuring it's a string before extracting years
claim_df['Purchase Year'] = claim_df['Purchase Date'].str[:4]  # Extract only the year

# Convert to numeric and check for anomalies
claim_df['Purchase Year'] = pd.to_numeric(claim_df['Purchase Year'], errors='coerce')
invalid_dates = claim_df[(claim_df['Purchase Year'] < 1900) | (claim_df['Purchase Year'] > 2100)]

print("Rows with invalid purchase dates:")
print(invalid_dates[['Purchase Date']])

Rows with invalid purchase dates:
              Purchase Date
194     9998-12-31 00:00:00
276     9998-12-31 00:00:00
7183    9998-12-31 00:00:00
7539    9998-12-31 00:00:00
11869   9998-12-31 00:00:00
24297   9998-12-31 00:00:00
43008   9998-12-31 00:00:00
108010  9998-12-31 00:00:00
144687  9998-12-31 00:00:00
160370  9998-12-31 00:00:00
170676  9998-12-31 00:00:00
208511  9998-12-31 00:00:00
239152  9998-12-31 00:00:00
269054  9998-12-31 00:00:00
354233  9998-12-31 00:00:00

In [47]:
# Replace invalid dates with NaT
claim_df.loc[(claim_df['Purchase Year'] < 1900) | (claim_df['Purchase Year'] > 2100), 'Purchase Date'] = pd.NaT

#cleaning the purchase date field
claim_df['Purchase Date'] = claim_df['Purchase Date'].astype(str).str.strip()
claim_df['Purchase Date'] = pd.to_datetime(claim_df['Purchase Date'], errors='coerce')
print(claim_df['Purchase Date'].dtype)  # Should now be datetime64[ns]

datetime64[ns]

In [48]:
# Removing time component from the date time

claim_df['Purchase Date'] = claim_df['Purchase Date'].dt.date
claim_df['Purchase Date'] = pd.to_datetime(claim_df['Purchase Date']).dt.normalize()

In [50]:
# Check for data type
print(f"updated data type for Purchase Date : {claim_df['Purchase Date'].dtype}")
# Check for missing values
missing_purchase_date = claim_df['Purchase Date'].isnull().sum()
print(f"Number of missing values in Purchase Date: {missing_purchase_date}")
claim_df['Purchase Date'].head()

updated data type for Purchase Date : datetime64[ns]
Number of missing values in Purchase Date: 15

0   2016-09-22
1   2019-01-16
2   2018-12-29
3   2018-05-08
4   2017-10-13
Name: Purchase Date, dtype: datetime64[ns]

### Failure Date

In [52]:
# Check missing values
missing_failure_date = claim_df['Failure Date'].isnull().sum()
print(f"Number of missing values in Failure Date: {missing_failure_date}")

# Check for the data type
print(f"Failure Date data type: {claim_df['Failure Date'].dtype}")

Number of missing values in Failure Date: 0
Failure Date data type: object

In [53]:
# It is incorrectly clasisfied as object, we need to convert to date format
# Pandas datetime format only supports dates within the range 1677-09-21 to 2262-04-11.
# Check for the purchase date column to find the invalid dates

import pandas as pd

# Check the unique years in the column
claim_df['Failure Date'] = claim_df['Failure Date'].astype(str)  # Ensure it's a string before extracting years
claim_df['Failure Year'] = claim_df['Failure Date'].str[:4]  # Extract only the year

# Convert to numeric and check for anomalies
claim_df['Failure Year'] = pd.to_numeric(claim_df['Failure Year'], errors='coerce')
invalid_dates = claim_df[(claim_df['Failure Year'] < 1900) | (claim_df['Failure Year'] > 2100)]

print("Rows with invalid purchase dates:")
print(invalid_dates[['Failure Date']])

Rows with invalid purchase dates:
              Failure Date
276    9998-12-31 00:00:00
24297  9998-12-31 00:00:00

In [54]:
# Replace invalid dates with NaT
claim_df.loc[(claim_df['Failure Year'] < 1900) | (claim_df['Failure Year'] > 2100), 'Failure Date'] = pd.NaT

In [56]:
claim_df['Failure Date'] = claim_df['Failure Date'].astype(str).str.strip()
claim_df['Failure Date'] = pd.to_datetime(claim_df['Failure Date'], errors='coerce')
print(claim_df['Failure Date'].dtype)  # Should now be datetime64[ns]

# Remove time component and keep only date

claim_df['Failure Date'] = claim_df['Failure Date'].dt.date
claim_df['Failure Date'] = pd.to_datetime(claim_df['Failure Date']).dt.normalize()

datetime64[ns]

In [57]:
# Check for data type
print(f"updated data type for Failuree Date : {claim_df['Failure Date'].dtype}")

# Check for missing values
missing_failure_date = claim_df['Failure Date'].isnull().sum()
print(f"Number of missing values in Failure Date: {missing_failure_date}")

updated data type for Failuree Date : datetime64[ns]
Number of missing values in Failure Date: 2

### Repair Date

In [ ]:
import pandas as pd

# Check missing values
missing_repair_date = claim_df['Repair Date'].isnull().sum()
print(f"Number of missing values in Repair Date: {missing_repair_date}")

# Check the data type
print(f"Repair Date data type before conversion: {claim_df['Repair Date'].dtype}")

Number of missing values in Repair Date: 0
Repair Date data type before conversion: object

In [58]:
# It is incorrectly clasisfied as object, we need to convert to date format

# Pandas datetime format only supports dates within the range 1677-09-21 to 2262-04-11.
# Check for the purchase date column to find the invalid dates

import pandas as pd

# Check the unique years in the column
claim_df['Repair Date'] = claim_df['Repair Date'].astype(str)  # Ensure it's a string before extracting years
claim_df['Repair Year'] = claim_df['Repair Date'].str[:4]  # Extract only the year

claim_df['Repair Year'] = pd.to_numeric(claim_df['Repair Year'], errors='coerce')
invalid_repair_dates = claim_df[(claim_df['Repair Year'] < 1900) | (claim_df['Repair Year'] > 2100)]
print("Rows with invalid repair dates:")
print(invalid_repair_dates[['Repair Date']])

Rows with invalid repair dates:
               Repair Date
24297  9998-12-31 00:00:00

In [59]:
# Replace invalid dates with NaT
claim_df.loc[(claim_df['Repair Year'] < 1900) | (claim_df['Repair Year'] > 2100), 'Repair Date'] = pd.NaT

# Convert the column to datetime format, handling errors
claim_df['Repair Date'] = pd.to_datetime(claim_df['Repair Date'], errors='coerce')

# Ensure the column is in datetime format
print(f"Repair Date data type after conversion: {claim_df['Repair Date'].dtype}")

# Final data type check
print(f"Updated data type for Repair Date: {claim_df['Repair Date'].dtype}")

# Check for missing values after cleaning
missing_repair_date = claim_df['Repair Date'].isnull().sum()
print(f"Number of missing values in Repair Date after cleaning: {missing_repair_date}")

Repair Date data type after conversion: datetime64[ns]
Updated data type for Repair Date: datetime64[ns]
Number of missing values in Repair Date after cleaning: 1

In [60]:
# Filter for repair dates less than 2019
repair_dates_less_than_2019 = claim_df[claim_df['Repair Date'] < pd.to_datetime('2019-01-01')]

# Print or further process the filtered data
repair_dates_less_than_2019['Repair Date']

# print as list
repair_dates_less_than_2019['Repair Date'].tolist()

# For 72 rows, though the repair data is from 2019 to 2024, it is updated same as failure or purchase date which is wrong
# we need to correct this data
# we will correcting this in excel (we will update the year and month based on Posted Calender Month abbr as it is much simpler

[Timestamp('2018-01-09 00:00:00'),
 Timestamp('2018-07-31 00:00:00'),
 Timestamp('2018-01-08 00:00:00'),
 Timestamp('2018-09-21 00:00:00'),
 Timestamp('2018-07-25 00:00:00'),
 Timestamp('2018-09-21 00:00:00'),
 Timestamp('2017-08-15 00:00:00'),
 Timestamp('2018-08-17 00:00:00'),
 Timestamp('2018-08-17 00:00:00'),
 Timestamp('2018-12-01 00:00:00'),
 Timestamp('2018-10-29 00:00:00'),
 Timestamp('2018-10-29 00:00:00'),
 Timestamp('2018-09-04 00:00:00'),
 Timestamp('2018-08-13 00:00:00'),
 Timestamp('2018-10-29 00:00:00'),
 Timestamp('2018-10-23 00:00:00'),
 Timestamp('2018-04-05 00:00:00'),
 Timestamp('2018-09-10 00:00:00'),
 Timestamp('2018-05-21 00:00:00'),
 Timestamp('2018-11-27 00:00:00'),
 Timestamp('2018-08-18 00:00:00'),
 Timestamp('2018-10-22 00:00:00'),
 Timestamp('2017-07-05 00:00:00'),
 Timestamp('2017-01-16 00:00:00'),
 Timestamp('2018-05-17 00:00:00'),
 Timestamp('2018-09-10 00:00:00'),
 Timestamp('2018-07-23 00:00:00'),
 Timestamp('2018-07-12 00:00:00'),
 Timestamp('2017-10-02 00:00:00'),
 Timestamp('2017-11-01 00:00:00'),
 Timestamp('2018-01-22 00:00:00'),
 Timestamp('2018-05-21 00:00:00'),
 Timestamp('2018-05-08 00:00:00'),
 Timestamp('2018-05-23 00:00:00'),
 Timestamp('2018-09-12 00:00:00'),
 Timestamp('2018-04-21 00:00:00'),
 Timestamp('2017-11-07 00:00:00'),
 Timestamp('2018-05-10 00:00:00'),
 Timestamp('2018-05-18 00:00:00'),
 Timestamp('2018-08-19 00:00:00'),
 Timestamp('2018-05-31 00:00:00'),
 Timestamp('2018-11-13 00:00:00'),
 Timestamp('2018-07-11 00:00:00'),
 Timestamp('2018-06-27 00:00:00'),
 Timestamp('2018-10-24 00:00:00'),
 Timestamp('2018-09-13 00:00:00'),
 Timestamp('2018-06-29 00:00:00'),
 Timestamp('2018-04-11 00:00:00'),
 Timestamp('2018-12-26 00:00:00'),
 Timestamp('2018-06-18 00:00:00'),
 Timestamp('2017-08-16 00:00:00'),
 Timestamp('2018-08-03 00:00:00'),
 Timestamp('2018-04-17 00:00:00'),
 Timestamp('2018-11-30 00:00:00'),
 Timestamp('2018-05-25 00:00:00'),
 Timestamp('2018-10-15 00:00:00'),
 Timestamp('2018-10-11 00:00:00'),
 Timestamp('2018-12-30 00:00:00'),
 Timestamp('2018-10-30 00:00:00'),
 Timestamp('2018-11-10 00:00:00'),
 Timestamp('2018-12-28 00:00:00'),
 Timestamp('2018-12-28 00:00:00'),
 Timestamp('2018-10-31 00:00:00'),
 Timestamp('2018-04-09 00:00:00'),
 Timestamp('2018-04-24 00:00:00'),
 Timestamp('2018-06-29 00:00:00'),
 Timestamp('2018-07-10 00:00:00'),
 Timestamp('2018-12-02 00:00:00'),
 Timestamp('2015-12-24 00:00:00'),
 Timestamp('2015-12-24 00:00:00'),
 Timestamp('2004-12-24 00:00:00'),
 Timestamp('2016-12-23 00:00:00')]

### Hours Used

In [61]:
# Print unique values
print(f"Total number of unique values in Hours Used :{claim_df['Hours Used'].nunique()}")

# Print missing values
missing_hours_used = claim_df['Hours Used'].isnull().sum()
print(f"Number of missing values in Hours Used: {missing_hours_used}")

# Print data type
print(f"Hours Used data type: {claim_df['Hours Used'].dtype}")

Total number of unique values in Hours Used :5270
Number of missing values in Hours Used: 0
Hours Used data type: float64

In [64]:
# Count of claim numbers with Hours used equal to 0

zero_hours_claims = claim_df[claim_df['Hours Used'] == 0]
count_zero_hours = len(zero_hours_claims)
print(f"Number of claim numbers with Hours Used equal to 0: {count_zero_hours}")

# Though it is a numeric data, we can see that more than 33% of the hours used is zero.
# Since it is manually updated data, many dealers did not update the hours used properly.
# We have excluded this row from our analysis

Number of claim numbers with Hours Used equal to 0: 124829

### Check Calendar Month Name Abbr

In [65]:
# Print unique values
print(f"Total number of unique values in Calendar Month Name Abbr :{claim_df['Check Calendar Month Name Abbr'].nunique()}")

# Missing value counts
missing_check_calendar_month_name_abbr = claim_df['Check Calendar Month Name Abbr'].isnull().sum()
print(f"Number of missing values in Check Calendar Month Name Abbr: {missing_check_calendar_month_name_abbr}")

# Data type
print(f"Check Calendar Month Name Abbr data type: {claim_df['Check Calendar Month Name Abbr'].dtype}")

Total number of unique values in Calendar Month Name Abbr :63
Number of missing values in Check Calendar Month Name Abbr: 0
Check Calendar Month Name Abbr data type: object

In [66]:
# Display unique values in the column
print(claim_df['Check Calendar Month Name Abbr'].unique())

['Apr/2020' 'Feb/2020' 'Nov/2019' 'Mar/2020' 'Jul/2020' 'Dec/2019'
 'Jun/2020' 'Jan/2020' 'May/2020' 'Aug/2020' 'Sep/2020' 'Oct/2020'
 'Nov/2020' 'Dec/2020' 'Ukn/9999' 'May/2021' 'Jan/2021' 'Feb/2021'
 'Mar/2021' 'Sep/2021' 'Apr/2021' 'Nov/2021' 'Apr/2022' 'Jun/2021'
 'Aug/2021' 'Feb/2023' 'Jul/2021' 'Oct/2021' 'Dec/2021' 'Mar/2023'
 'Jun/2022' 'Jan/2022' 'Jan/2024' 'Feb/2022' 'Mar/2022' 'Oct/2024'
 'May/2022' 'Dec/2022' 'Jul/2022' 'Aug/2022' 'Oct/2022' 'Sep/2022'
 'Nov/2022' 'Jan/2023' 'Feb/2024' 'Apr/2023' 'Aug/2023' 'Dec/2023'
 'May/2023' 'Jun/2023' 'Nov/2023' 'Jul/2023' 'Sep/2023' 'Oct/2023'
 'May/2024' 'Apr/2024' 'Mar/2024' 'Jun/2024' 'Aug/2024' 'Jul/2024'
 'Sep/2024' 'Nov/2024' 'Dec/2024']

In [67]:
import numpy as np

# Replace the invalid value "Ukn/9999" with NaN
claim_df['Check Calendar Month Name Abbr'] = claim_df['Check Calendar Month Name Abbr'].replace('Ukn/9999', np.nan)

# Verify the change
print(f"Missing values count after replacement: {claim_df['Check Calendar Month Name Abbr'].isna().sum()}")

Missing values count after replacement: 59

In [68]:
# Convert valid dates to datetime format
claim_df['Check Calendar Month Name Abbr'] = pd.to_datetime(claim_df['Check Calendar Month Name Abbr'], format='%b/%Y', errors='coerce')

# Verify conversion
print(claim_df['Check Calendar Month Name Abbr'].dtype)  # Should be datetime64[ns]
print(claim_df['Check Calendar Month Name Abbr'].head())

datetime64[ns]
0   2020-04-01
1   2020-02-01
2   2019-11-01
3   2019-11-01
4   2019-11-01
Name: Check Calendar Month Name Abbr, dtype: datetime64[ns]

In [69]:
claim_df['Check Calendar Month Name Abbr'] = claim_df['Check Calendar Month Name Abbr'].dt.to_period('M')

# Verify conversion
print(claim_df['Check Calendar Month Name Abbr'].dtype)  # Should be period[M]

period[M]

In [70]:
# Check if any NaN values remain
print(claim_df['Check Calendar Month Name Abbr'].isna().sum(), "rows have missing values after conversion")

# Data type
print(f"Updated data type for Check Calendar Month Name Abbr: {claim_df['Check Calendar Month Name Abbr'].dtype}")

59 rows have missing values after conversion
Updated data type for Check Calendar Month Name Abbr: period[M]

### Posted Calendar Month Name Abbr

In [71]:
# Print unique values
print(f"Total number of unique values in Calendar Month Name Abbr :{claim_df['Posted Calendar Month Name Abbr'].nunique()}")

# Missing value counts
missing_Posted_calendar_month_name_abbr = claim_df['Posted Calendar Month Name Abbr'].isnull().sum()
print(f"Number of missing values in Check Calendar Month Name Abbr: {missing_Posted_calendar_month_name_abbr}")

# Data type
print(f"Posted Calendar Month Name Abbr data type: {claim_df['Posted Calendar Month Name Abbr'].dtype}")

Total number of unique values in Calendar Month Name Abbr :61
Number of missing values in Check Calendar Month Name Abbr: 0
Posted Calendar Month Name Abbr data type: object

In [72]:
# Display unique values in the column
print(claim_df['Posted Calendar Month Name Abbr'].unique())

# We don't have any invalid values in the data

['Apr/2020' 'Feb/2020' 'Nov/2019' 'Mar/2020' 'Jul/2020' 'Dec/2019'
 'Jun/2020' 'Jan/2020' 'May/2020' 'Aug/2020' 'Sep/2020' 'Oct/2020'
 'Nov/2020' 'Dec/2020' 'May/2021' 'Jun/2021' 'Feb/2021' 'Jul/2021'
 'Jan/2021' 'Mar/2021' 'Apr/2021' 'Oct/2021' 'Aug/2021' 'Sep/2021'
 'Nov/2021' 'Dec/2021' 'Feb/2022' 'Jan/2022' 'Mar/2022' 'Jun/2022'
 'Apr/2022' 'May/2022' 'Dec/2022' 'Jul/2022' 'Aug/2022' 'Oct/2022'
 'Sep/2022' 'Nov/2022' 'Jan/2023' 'Feb/2023' 'Mar/2023' 'Apr/2023'
 'Aug/2023' 'May/2023' 'Jun/2023' 'Nov/2023' 'Jul/2023' 'Sep/2023'
 'Oct/2023' 'Dec/2023' 'Feb/2024' 'Jan/2024' 'Mar/2024' 'Apr/2024'
 'May/2024' 'Jun/2024' 'Aug/2024' 'Jul/2024' 'Sep/2024' 'Oct/2024'
 'Nov/2024']

In [73]:
# Convert valid dates to datetime format

claim_df['Posted Calendar Month Name Abbr'] = pd.to_datetime(claim_df['Posted Calendar Month Name Abbr'], format='%b/%Y', errors='coerce')

# Verify conversion
print(claim_df['Posted Calendar Month Name Abbr'].dtype)  # Should be datetime64[ns]
print(claim_df['Posted Calendar Month Name Abbr'].head())

datetime64[ns]
0   2020-04-01
1   2020-02-01
2   2019-11-01
3   2019-11-01
4   2019-11-01
Name: Posted Calendar Month Name Abbr, dtype: datetime64[ns]

In [ ]:
claim_df['Posted Calendar Month Name Abbr'] = claim_df['Posted Calendar Month Name Abbr'].dt.to_period('M')

# Verify conversion
print(claim_df['Posted Calendar Month Name Abbr'].dtype)  # Should be period[M]

period[M]

In [76]:
# Check if any NaN values remain
print(claim_df['Posted Calendar Month Name Abbr'].isna().sum(), "rows have missing values after conversion")

# Data type
print(f"Updated data type for Posted Calendar Month Name Abbr: {claim_df['Posted Calendar Month Name Abbr'].dtype}")

0 rows have missing values after conversion
Updated data type for Posted Calendar Month Name Abbr: datetime64[ns]

In [78]:
# Dropping Check Calendar Month Name Abbr
# As we can see both columns are highly correlated, hence, we are dropping Check Calendar Month Name Abbr

claim_df.drop('Check Calendar Month Name Abbr', axis=1, inplace=True)

### Deliver Cost - Dropping the Column

In [79]:
# Print unique values
print(f"Total number of unique values in Deliver Cost :{claim_df['Deliver Cost'].nunique()}")

# Print missing values
missing_deliver_cost = claim_df['Deliver Cost'].isnull().sum()
print(f"Number of missing values in Deliver Cost: {missing_deliver_cost}")

# Print data type
print(f"Deliver Cost data type: {claim_df['Deliver Cost'].dtype}")

Total number of unique values in Deliver Cost :86
Number of missing values in Deliver Cost: 0
Deliver Cost data type: float64

In [80]:
# Count of rows with Deliver cost equal to 0
# Count of claim numbers  with Hours used equal to 0

Zero_Deliver_Cost_claims = claim_df[claim_df['Deliver Cost'] == 0]
count_Zero_Deliver_Cost = len(Zero_Deliver_Cost_claims)
print(f"Number of claim numbers with Deliver Cost Used equal to 0: {count_Zero_Deliver_Cost}")

# Out of 375364 rows, 365957 rows has deliver cost as 0.
# Hence, we can drop this column.

Number of claim numbers with Deliver Cost Used equal to 0: 365957

In [81]:
# Drop Deliver Cost

claim_df.drop('Deliver Cost', axis=1, inplace=True)

### Total Claim Dollars

In [82]:
# Print unqiue values
print(f"Total number of unique values in Total Claim Dollars :{claim_df['Total Claim Dollars'].nunique()}")

# Print missing data
missing_total_claim_dollars = claim_df['Total Claim Dollars'].isnull().sum()
print(f"Number of missing values in Total Claim Dollars: {missing_total_claim_dollars}")

# Print data type
print(f"Total Claim Dollars data type: {claim_df['Total Claim Dollars'].dtype}")

Total number of unique values in Total Claim Dollars :67828
Number of missing values in Total Claim Dollars: 0
Total Claim Dollars data type: float64

In [87]:
claim_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375364 entries, 0 to 375363
Data columns (total 18 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Claim Number                     375364 non-null  int64
 1   Model Number                     375348 non-null  object
 2   Warranty Item Description        375364 non-null  object
 3   Serial Number                    375364 non-null  object
 4   Engine Model                     333224 non-null  object
 5   Engine Serial                    335070 non-null  object
 6   Transmission Model               279142 non-null  object
 7   Transmission Serial              279406 non-null  object
 8   Repair Dealer Number             368636 non-null  object
 9   Owner City                       305478 non-null  object
 10  Owner State                      305381 non-null  object
 11  Owner Zip                        305481 non-null  object
 12  Purchase Date                    375349 non-null  datetime64[ns]
 13  Failure Date                     375362 non-null  datetime64[ns]
 14  Repair Date                      375363 non-null  datetime64[ns]
 15  Hours Used                       375364 non-null  float64
 16  Posted Calendar Month Name Abbr  375364 non-null  datetime64[ns]
 17  Total Claim Dollars              375364 non-null  float64
dtypes: datetime64[ns](4), float64(2), int64(1), object(11)
memory usage: 51.5+ MB

In [88]:
# drop purchase year, failure year, repair year as they need a little cleaning in excel
claim_df.drop(['Purchase Year', 'Failure Year', 'Repair Year'], axis=1, inplace=True)

KeyError: "['Purchase Year', 'Failure Year', 'Repair Year'] not found in axis"

In [89]:
# check the info again
claim_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375364 entries, 0 to 375363
Data columns (total 18 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Claim Number                     375364 non-null  int64
 1   Model Number                     375348 non-null  object
 2   Warranty Item Description        375364 non-null  object
 3   Serial Number                    375364 non-null  object
 4   Engine Model                     333224 non-null  object
 5   Engine Serial                    335070 non-null  object
 6   Transmission Model               279142 non-null  object
 7   Transmission Serial              279406 non-null  object
 8   Repair Dealer Number             368636 non-null  object
 9   Owner City                       305478 non-null  object
 10  Owner State                      305381 non-null  object
 11  Owner Zip                        305481 non-null  object
 12  Purchase Date                    375349 non-null  datetime64[ns]
 13  Failure Date                     375362 non-null  datetime64[ns]
 14  Repair Date                      375363 non-null  datetime64[ns]
 15  Hours Used                       375364 non-null  float64
 16  Posted Calendar Month Name Abbr  375364 non-null  datetime64[ns]
 17  Total Claim Dollars              375364 non-null  float64
dtypes: datetime64[ns](4), float64(2), int64(1), object(11)
memory usage: 51.5+ MB

In [90]:
claim_df.head()

,Claim Number,Model Number,Warranty Item Description,Serial Number,Engine Model,Engine Serial,Transmission Model,Transmission Serial,Repair Dealer Number,Owner City,Owner State,Owner Zip,Purchase Date,Failure Date,Repair Date,Hours Used,Posted Calendar Month Name Abbr,Total Claim Dollars
0,20028686,13C226JD333,MOWER:MINI LT:30SD 6SPD J STYL,1K045B20348,752Z4P90JUD,4P90JUD1502111B0052,618-05056B,1H255Q11381,S40899,WANDAL,QL,4700,2016-09-22,2018-01-03,2018-01-09,20.0,2020-04-01,218.98
1,20032406,11AEE1L4333,MOWER:159CC ENG 18 IN,1B125P10128,752L2P65WT,2P65WT 1501221A0083,NaN,NaN,S41744,CECIL HILLS,NS,2171,2019-01-16,2019-01-16,2019-01-17,0.0,2020-02-01,73.96
2,20032941,13A276WF333,MOWER:LT5:38SD 6SPD W STYLE,1F018B40253,752Z4P90HUD,1803143A0170,618-04914A,0E018Q110519,S40655,NEW BEITH,QL,4124,2018-12-29,2019-03-15,2019-03-15,11.0,2019-11-01,75.75
3,30843126,41BS2BVG799,316.791770:27CC:MPP:BV:149:14,1F097DF1822,NaN,-,NaN,NaN,S03730,VADNAIS HEIGHTS,MN,55127,2018-05-08,2019-10-08,2019-11-06,5.0,2019-11-01,34.20
4,20033818,53AWEFJA330,MOWER:PZFS:54FAB HYD J STYLE,1F237H30036,NaN,4715211413,618-07112A,7095D50230,S43090,WARRAGUL,VI,3820,2017-10-13,2019-06-12,2019-06-21,45.0,2019-11-01,777.79

In [ ]:
# prompt: # download my updated claim df to my local

from google.colab import files
claim_df.to_csv('claim_df.csv', encoding = 'utf-8-sig')
files.download('claim_df.csv')

we will be downloading the claim_df into our local and will be cleaning 2 columns in excel further to get the final cleaned data frame.

Columns to be cleaned further using excel
1. Owner city - we will update the city correctly for 148 rows where either zip code or street name is mentioned
2. Repair Date - we will clean all the 72 rows where Repair date mentioned incorrectly (with values from purchase or failure date) instead of actual repair date. we will update this column based on Posted Calender Month Abbrv.

## Now let's get started with Failure Part Data

In [91]:
failure_part_df.head()

,Failure Part id,Claim Number,Failure Description,Failure Part,Failure Part Description,Complaint Diagnosis,Work Performed,Vendor Number
0,1,20028686,Loose,757-04083A,SEAT:3400:MED BACK:BLK NO OPS,guide inserts broken off seat,removed seat due to its sliding when custome...,10403.0
1,2,20032406,Damaged at Factory,925-04347,SW:KEY:MOMENTARY,"TRACE FAULT, DEFECTIVE IGNITION SWITCH, REPL...","TRY TO KEY START UNIT WOULDNT TURN OVER, TRA...",547628.0
2,3,20032941,Will not Charge,925-1707D,BAT:U1:300 CCA DRY VENTED T UD,Faulty battery.,"Charged battery, tested faulty at 108CCA. Te...",725200.0
3,4,30843126,Cracked,753-06687,SHBLK:FC27CC:SC BLO,Found engine has a broken connecting rod. co...,Cylinder/Piston Service (2cycle),0.0
4,5,20033818,Incorrect Part,951-12725,"CAP:FUEL:3.50"" ONEWAY VENT FKM",Fuel Cap recall,Replaced fuel caps to breathe correctly as p...,547628.0

In [92]:
# Info
failure_part_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395279 entries, 0 to 395278
Data columns (total 8 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Failure Part id           395279 non-null  int64
 1   Claim Number              395279 non-null  int64
 2   Failure Description       395279 non-null  object
 3   Failure Part              395190 non-null  object
 4   Failure Part Description  395279 non-null  object
 5   Complaint Diagnosis       395279 non-null  object
 6   Work Performed            395279 non-null  object
 7   Vendor Number             394920 non-null  float64
dtypes: float64(1), int64(2), object(5)
memory usage: 24.1+ MB

### Failure Description

In [ ]:
# Failure Description Unique Values
print(f"Total number of unique values in Failure Description :{failure_part_df['Failure Description'].nunique()}")

# Missing values
missing_failure_description = failure_part_df['Failure Description'].isnull().sum()
print(f"Number of missing values in Failure Description: {missing_failure_description}")

# Data type
print(f"Failure Description data type: {failure_part_df['Failure Description'].dtype}")

Total number of unique values in Failure Description :67
Number of missing values in Failure Description: 0
Failure Description data type: object

### Failure Part

In [93]:
# Failure Part Unique
print(f"Total number of unique values in Failure Part :{failure_part_df['Failure Part'].nunique()}")

# Missing values
missing_failure_part = failure_part_df['Failure Part'].isnull().sum()
print(f"Number of missing values in Failure Part: {missing_failure_part}")
# Data type
print(f"Failure Part data type: {failure_part_df['Failure Part'].dtype}")

# We can see there are 89 missing values in Failure Part

# Print the head where failure part is blank
failure_part_df[failure_part_df['Failure Part'].isnull()].head(200)

# All the missing values in Failure Part are for one part only "PROTOTYPE MOWERS"

Total number of unique values in Failure Part :18617
Number of missing values in Failure Part: 89
Failure Part data type: object

,Failure Part id,Claim Number,Failure Description,Failure Part,Failure Part Description,Complaint Diagnosis,Work Performed,Vendor Number
9,10,20034228,Leaking,NaN,PROTOTYPE MOWERS,leaking fuel into engine sump sticking needle,Fuel Line,0.0
865,866,20035908,Leaking,NaN,PROTOTYPE MOWERS,LEAKING FROM CARBURETTOR.,FOUND DIRT PARTICLES IN TANK/CARBY. CLEAN OU...,0.0
3206,3207,30841867,PDI/Dealer Prep,NaN,PROTOTYPE MOWERS,Filing for trip charge only. Case 04926598 4...,Filing for trip charge only. Case Number 049...,0.0
11176,11177,30852749,Missing,NaN,PROTOTYPE MOWERS,CUSTOMER BROUGHT IN MOWER AND STATED THE FRO...,Handle Bracket/Height Adjuster Assemblies,0.0
14719,14720,30857156,Insufficient Lube,NaN,PROTOTYPE MOWERS,CHAIN OILER INOPERABLE NOT OILING CHAIN CAUS...,Valve Service/Troubleshoot (4cycle),0.0
...,...,...,...,...,...,...,...,...
391210,391211,93125953,Supplier Defect,NaN,PROTOTYPE MOWERS,le gouverneur ne travaille pas sur le moteur...,d monter le bras du gouverneur pour replacer...,0.0
391236,391237,93125988,Backed Out,NaN,PROTOTYPE MOWERS,TECHNICIAN INSPECTED - FOUND BOLTS FOR TRANS...,Engine Pulley/Drive Pulley(s),0.0
394652,394653,93130760,Mis-Assembled,NaN,PROTOTYPE MOWERS,OIL LEAK AT VALVE COVER,REMOVED VALVE COVER AND RESEALED,0.0
394837,394838,93131069,Adjustment,NaN,PROTOTYPE MOWERS,,"REMOVED AND INSPECTED BELT ,SPINDLES ,PTO, C...",0.0
395001,395002,93131319,Loose,NaN,PROTOTYPE MOWERS,NEUTRAL LINKAGE FELL OFF. REPAIRED LINKAGE A...,Neutral Bracket R & I,0.0

In [94]:
# convert the all the missing values in Failure part to Prototype Mowers

# Fill missing 'Failure Part' values with 'Prototype Mowers'
failure_part_df['Failure Part'].fillna('Prototype Mowers', inplace=True)

# Verify the changes
missing_failure_part = failure_part_df['Failure Part'].isnull().sum()
print(f"Number of missing values in Failure Part after filling: {missing_failure_part}")

Number of missing values in Failure Part after filling: 0

<ipython-input-94-c060c2838951>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  failure_part_df['Failure Part'].fillna('Prototype Mowers', inplace=True)

### Vendor Number

In [95]:
# Convert Vendor Number into a 6 digit value for all rows

failure_part_df['Vendor Number'] = failure_part_df['Vendor Number'].apply(
    lambda x: f"{int(x):06d}" if pd.notna(x) else x
)

# Verify the changes
print(failure_part_df[['Vendor Number']].head(10))  # Checking first 10 rows

  Vendor Number
0        010403
1        547628
2        725200
3        000000
4        547628
5        435102
6        000000
7        547628
8        000000
9        000000

In [96]:
# missing values in vendors
missing_vendor_number = failure_part_df['Vendor Number'].isnull().sum()
print(f"Number of missing values in Vendor Number: {missing_vendor_number}")

# check for unique values in vendor
print(f"Total number of unique values in Vendor Number :{failure_part_df['Vendor Number'].nunique()}")

# check data type
print(f"Vendor Number data type: {failure_part_df['Vendor Number'].dtype}")

Number of missing values in Vendor Number: 359
Total number of unique values in Vendor Number :655
Vendor Number data type: object

### Complaint Diagnosis

In [97]:
# missing values
missing_complaint_diagnosis = failure_part_df['Complaint Diagnosis'].isnull().sum()
print(f"Number of missing values in Complaint Diagnosis: {missing_complaint_diagnosis}")

# data type
print(f"Complaint Diagnosis data type: {failure_part_df['Complaint Diagnosis'].dtype}")

Number of missing values in Complaint Diagnosis: 0
Complaint Diagnosis data type: object

### work performed

In [98]:
# missing values
missing_work_performed = failure_part_df['Work Performed'].isnull().sum()
print(f"Number of missing values in Work Performed: {missing_work_performed}")

# data type
print(f"Work Performed data type: {failure_part_df['Work Performed'].dtype}")

Number of missing values in Work Performed: 0
Work Performed data type: object

In [99]:
# check info again
failure_part_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395279 entries, 0 to 395278
Data columns (total 8 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Failure Part id           395279 non-null  int64
 1   Claim Number              395279 non-null  int64
 2   Failure Description       395279 non-null  object
 3   Failure Part              395279 non-null  object
 4   Failure Part Description  395279 non-null  object
 5   Complaint Diagnosis       395279 non-null  object
 6   Work Performed            395279 non-null  object
 7   Vendor Number             394920 non-null  object
dtypes: int64(2), object(6)
memory usage: 24.1+ MB

## Now, Let's Start with Replacement Part Data

In [101]:
replacement_part_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699993 entries, 0 to 699992
Data columns (total 10 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Claim Number                  699993 non-null  int64
 1   Replacement Part id           699993 non-null  int64
 2   Replacement Part              699902 non-null  object
 3   Replacement Part Description  699993 non-null  object
 4   Part Quantity                 699993 non-null  int64
 5   Part Price                    699993 non-null  float64
 6   Part Extended Price           699993 non-null  float64
 7   Labor Rate                    699993 non-null  int64
 8   Paid Labor Hours              395279 non-null  float64
 9   Total Failure Cost            699992 non-null  float64
dtypes: float64(4), int64(4), object(2)
memory usage: 53.4+ MB

In [ ]:
replacement_part_df.columns = replacement_part_df.columns.str.strip()

### Replacement Part

In [100]:
# unique values
print(f"Total number of unique values in Replacement Part :{replacement_part_df['Replacement Part'].nunique()}")

# missing values
missing_replacement_part = replacement_part_df['Replacement Part'].isnull().sum()
print(f"Number of missing values in Replacement Part: {missing_replacement_part}")

# data type
print(f"Replacement Part data type: {replacement_part_df['Replacement Part'].dtype}")

Total number of unique values in Replacement Part :35502
Number of missing values in Replacement Part: 91
Replacement Part data type: object

In [102]:
# print all rows where replacement part is blank
replacement_part_df[replacement_part_df['Replacement Part'].isnull()]

# as we can see here, all the 91 rows where the replacement part is missing, it belongs to same type "Prototype Mowers"

,Claim Number,Replacement Part id,Replacement Part,Replacement Part Description,Part Quantity,Part Price,Part Extended Price,Labor Rate,Paid Labor Hours,Total Failure Cost
18,20034228,19,NaN,PROTOTYPE MOWERS,1,0.0,0.0,60,NaN,0.0
1380,20035908,1381,NaN,PROTOTYPE MOWERS,1,0.0,0.0,60,1.00,60.0
5344,30841867,5345,NaN,PROTOTYPE MOWERS,1,0.0,0.0,70,NaN,0.0
17526,30852749,17527,NaN,PROTOTYPE MOWERS,1,0.0,0.0,78,0.50,39.0
21494,30856194,21495,NaN,PROTOTYPE MOWERS,1,0.0,0.0,80,1.00,80.0
...,...,...,...,...,...,...,...,...,...,...
693059,93125953,693060,NaN,PROTOTYPE MOWERS,1,0.0,0.0,79,0.50,39.5
693105,93125988,693106,NaN,PROTOTYPE MOWERS,1,0.0,0.0,110,1.60,176.0
698971,93130760,698972,NaN,PROTOTYPE MOWERS,1,0.0,0.0,110,0.50,55.0
699291,93131069,699292,NaN,PROTOTYPE MOWERS,1,0.0,0.0,95,1.00,95.0
699548,93131319,699549,NaN,PROTOTYPE MOWERS,1,0.0,0.0,100,0.45,45.0

In [103]:
# convert the all the missing values in Replacement Part to Prototype Mowers

# Fill missing 'Replacement Part' values with 'Prototype Mowers'
replacement_part_df['Replacement Part'].fillna('Prototype Mowers', inplace=True)

# Verify the changes
missing_replacement_part = replacement_part_df['Replacement Part'].isnull().sum()
print(f"Number of missing values in Replacement Part after filling: {missing_replacement_part}")

Number of missing values in Replacement Part after filling: 0

<ipython-input-103-2cf7ca336578>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  replacement_part_df['Replacement Part'].fillna('Prototype Mowers', inplace=True)

### Replacement Part Description

In [104]:
# unique values
print(f"Total number of unique values in Replacement Part Description :{replacement_part_df['Replacement Part Description'].nunique()}")

# missing values
missing_replacement_part_description = replacement_part_df['Replacement Part Description'].isnull().sum()
print(f"Number of missing values in Replacement Part Description: {missing_replacement_part_description}")

# data type
print(f"Replacement Part Description data type: {replacement_part_df['Replacement Part Description'].dtype}")

Total number of unique values in Replacement Part Description :16427
Number of missing values in Replacement Part Description: 0
Replacement Part Description data type: object

### part Quantity

In [105]:
# unique
print(f"Total number of unique values in Part Quantity :{replacement_part_df['Part Quantity'].nunique()}")

# missing
missing_part_quantity = replacement_part_df['Part Quantity'].isnull().sum()
print(f"Number of missing values in Part Quantity: {missing_part_quantity}")

# data type
print(f"Part Quantity data type: {replacement_part_df['Part Quantity'].dtype}")

Total number of unique values in Part Quantity :56
Number of missing values in Part Quantity: 0
Part Quantity data type: int64

### Part Price

In [106]:
# unique
print(f"Total number of unique values in Part Price :{replacement_part_df['Part Price'].nunique()}")

# missing
missing_part_price = replacement_part_df['Part Price'].isnull().sum()
print(f"Number of missing values in Part Price: {missing_part_price}")

# data type
print(f"Part Price data type: {replacement_part_df['Part Price'].dtype}")

Total number of unique values in Part Price :20580
Number of missing values in Part Price: 0
Part Price data type: float64

### Part Extended Price

In [107]:
# unique
print(f"Total number of unique values in Part Extended Price :{replacement_part_df['Part Extended Price'].nunique()}")

# missing
missing_part_extended_price = replacement_part_df['Part Extended Price'].isnull().sum()
print(f"Number of missing values in Part Extended Price: {missing_part_extended_price}")

# data type
print(f"Part Extended Price data type: {replacement_part_df['Part Extended Price'].dtype}")

Total number of unique values in Part Extended Price :21847
Number of missing values in Part Extended Price: 0
Part Extended Price data type: float64

### Labor Rate

In [108]:
# unique
print(f"Total number of unique values in Labor Rate :{replacement_part_df['Labor Rate'].nunique()}")

# missing
missing_labor_rate = replacement_part_df['Labor Rate'].isnull().sum()
print(f"Number of missing values in Labor Rate: {missing_labor_rate}")

# data type
print(f"Labor Rate data type: {replacement_part_df['Labor Rate'].dtype}")

Total number of unique values in Labor Rate :121
Number of missing values in Labor Rate: 0
Labor Rate data type: int64

### Paid labor Hours

In [109]:
# missing
missing_paid_labor_hours = replacement_part_df['Paid Labor Hours'].isnull().sum()
print(f"Number of missing values in Paid Labor Hours: {missing_paid_labor_hours}")

# unique
print(f"Total number of unique values in Paid Labor Hours :{replacement_part_df['Paid Labor Hours'].nunique()}")

# data type
print(f"Paid Labor Hours data type: {replacement_part_df['Paid Labor Hours'].dtype}")

Number of missing values in Paid Labor Hours: 304714
Total number of unique values in Paid Labor Hours :549
Paid Labor Hours data type: float64

### Total Failure Cost

In [112]:
replacement_part_df.columns

Index(['Claim Number', 'Replacement Part id', 'Replacement Part',
       'Replacement Part Description', 'Part Quantity', 'Part Price',
       'Part Extended Price', 'Labor Rate', 'Paid Labor Hours',
       'Total Failure Cost '],
      dtype='object')

In [115]:
# unique
print(f"Total number of unique values in Total Failure Cost :{replacement_part_df['Total Failure Cost '].nunique()}")

# missing
missing_total_failure_cost = replacement_part_df['Total Failure Cost '].isnull().sum()
print(f"Number of missing values in Total Failure Cost: {missing_total_failure_cost}")

# data type
print(f"Total Failure Cost data type: {replacement_part_df['Total Failure Cost '].dtype}")

Total number of unique values in Total Failure Cost :62128
Number of missing values in Total Failure Cost: 1
Total Failure Cost data type: float64

In [ ]:
# prompt: download the failure and replacement data to local

failure_part_df.to_csv('failure_part_cleaned_df.csv', encoding = 'utf-8-sig')
files.download('failure_part_cleaned_df.csv')

replacement_part_df.to_csv('replacement_part_cleaned_df.csv', encoding = 'utf-8-sig')
files.download('replacement_part_cleaned_df.csv')