In [1]:
from google.colab import drive
drive.mount('/content/drive')

# Import the Pandas library
import pandas as pd

# load file from google drive
claim_cleaned_df_path = "/content/drive/My Drive/SBD_CAPSTONE/Cleaned_Data/claim_cleaned_df.csv"

# Load the file using read_csv since it's a CSV file
claim_cleaned_df = pd.read_csv(claim_cleaned_df_path)

# Display the first few rows of the dataframe
print(claim_cleaned_df.head())

Mounted at /content/drive
   Claim Number Model Number    Warranty Item Description Serial Number  \
0      71692559  55RK6HNR050  MOWER:CWB:36 HYD2800 RECOIL   1B198H70003
1      71698531  55RK6HNR050  MOWER:CWB:36 HYD2800 RECOIL   1B198H70003
2      71700308  55RK6HNR050  MOWER:CWB:36 HYD2800 RECOIL   1B198H70003
3      71707104  55RK6HNR050  MOWER:CWB:36 HYD2800 RECOIL   1B198H70003
4      71726990  55RK6HNR050  MOWER:CWB:36 HYD2800 RECOIL   1B158H70028

   Engine Model Transmission Model Repair Dealer Number  \
0  752SFS481S33          618-07347               S76489
1  752SFS481S33          618-07347               S76489
2  752SFS481S33          618-07347               S76489
3  752SFS481S33          618-07347               S76489
4  752SFS481S33          618-07347               S77690

                  Owner City Owner State Owner Zip Purchase Date Failure Date  \
0  ANDOVER                            KS     67002     7/13/2019    7/18/2020
1  ANDOVER                            KS     67002     7/13/2019    7/18/2020
2  ANDOVER                            KS     67002     7/13/2019    7/18/2020
3  ANDOVER                            KS     67002     7/13/2019    9/26/2020
4  APEX                               NC     27502      5/1/2020    6/24/2020

  Repair Date  Hours Used Posted Calendar Month Name Abbr  Total Claim Dollars
0   7/18/2020       431.1                         2020-08                98.86
1    8/1/2020       431.1                         2020-09                27.98
2    8/1/2020       431.1                         2020-09               183.94
3   9/26/2020       450.0                         2020-10                69.50
4    2/1/2021         0.0                         2021-02               169.26

In [2]:
# Import the Pandas library

import pandas as pd

# load the file from google drive

failure_part_cleaned_path = "/content/drive/My Drive/SBD_CAPSTONE/Cleaned_Data/failure_part_cleaned_df.csv"
failure_part_cleaned_df = pd.read_csv(failure_part_cleaned_path)

# display first few rows

print(failure_part_cleaned_df.head())

   Unnamed: 0  Failure Part id   Claim Number             Failure Description  \
0           0                 1      20028686  Loose
1           1                 2      20032406  Damaged at Factory
2           2                 3      20032941  Will not Charge
3           3                 4      30843126  Cracked
4           4                 5      20033818  Incorrect Part

  Failure Part        Failure Part Description  \
0   757-04083A   SEAT:3400:MED BACK:BLK NO OPS
1    925-04347                SW:KEY:MOMENTARY
2    925-1707D  BAT:U1:300 CCA DRY VENTED T UD
3    753-06687             SHBLK:FC27CC:SC BLO
4    951-12725  CAP:FUEL:3.50" ONEWAY VENT FKM

                                 Complaint Diagnosis  \
0                      guide inserts broken off seat
1    TRACE FAULT, DEFECTIVE IGNITION SWITCH, REPL...
2                                    Faulty battery.
3    Found engine has a broken connecting rod. co...
4                                    Fuel Cap recall

                                      Work Performed  Vendor Number
0    removed seat due to its sliding when custome...        10403.0
1    TRY TO KEY START UNIT WOULDNT TURN OVER, TRA...       547628.0
2    Charged battery, tested faulty at 108CCA. Te...       725200.0
3                   Cylinder/Piston Service (2cycle)            0.0
4    Replaced fuel caps to breathe correctly as p...       547628.0

In [3]:
# load the file from google drive

replacement_part_cleaned_data = "/content/drive/My Drive/SBD_CAPSTONE/Cleaned_Data/replacement_part_cleaned_df.csv"
replacement_part_cleaned_df = pd.read_csv(replacement_part_cleaned_data)

# display the first few rows

print(replacement_part_cleaned_df.head())

   Unnamed: 0  Claim Number  Replacement Part id Replacement Part  \
0           0      20028686                    1       757-04083A
1           1      20032406                    2        925-04347
2           2      20032941                    3        925-1707D
3           3      30843126                    4        753-06687
4           4      20033818                    5        951-12725

     Replacement Part Description  Part Quantity  Part Price  \
0   SEAT:3400:MED BACK:BLK NO OPS              1      169.07
1                SW:KEY:MOMENTARY              1       22.24
2  BAT:U1:300 CCA DRY VENTED T UD              1       49.06
3             SHBLK:FC27CC:SC BLO              1        0.00
4  CAP:FUEL:3.50" ONEWAY VENT FKM              2       51.59

   Part Extended Price  Labor Rate  Paid Labor Hours  Total Failure Cost
0               169.07          60              0.50              199.07
1                22.24          60              0.75               67.24
2                49.06          60              0.33               68.86
3                 0.00          76              0.25               19.00
4               103.18          60              0.25              118.18

In [4]:
claim_cleaned_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375364 entries, 0 to 375363
Data columns (total 16 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Claim Number                     375364 non-null  int64
 1   Model Number                     375348 non-null  object
 2   Warranty Item Description        375364 non-null  object
 3   Serial Number                    374033 non-null  object
 4   Engine Model                     333224 non-null  object
 5   Transmission Model               277260 non-null  object
 6   Repair Dealer Number             368636 non-null  object
 7   Owner City                       305478 non-null  object
 8   Owner State                      305381 non-null  object
 9   Owner Zip                        305481 non-null  object
 10  Purchase Date                    375349 non-null  object
 11  Failure Date                     375362 non-null  object
 12  Repair Date                      375364 non-null  object
 13  Hours Used                       375364 non-null  float64
 14  Posted Calendar Month Name Abbr  375364 non-null  object
 15  Total Claim Dollars              375364 non-null  float64
dtypes: float64(2), int64(1), object(13)
memory usage: 45.8+ MB

In [5]:
import pandas as pd

# many rows have a lot of extra space which we are removing in this step

# strip the unwanted space from row values

claim_cleaned_df = claim_cleaned_df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

<ipython-input-5-23a1cf89e242>:7: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  claim_cleaned_df = claim_cleaned_df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

In [6]:
import pandas as pd

# apply the same for failure data

failure_part_cleaned_df = failure_part_cleaned_df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

<ipython-input-6-e9d1b662d2ae>:5: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  failure_part_cleaned_df = failure_part_cleaned_df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

In [7]:
import pandas as pd

# Apply the same to replacement data

replacement_part_cleaned_df = replacement_part_cleaned_df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

<ipython-input-7-173d5c2399be>:5: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  replacement_part_cleaned_df = replacement_part_cleaned_df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

## Feature Engineering

## 1. Number of days of Usage

In [8]:
# number of days of usage by subsracting purchase date and failure date

# Convert 'Purchase Date' to datetime
claim_cleaned_df['Purchase Date'] = pd.to_datetime(claim_cleaned_df['Purchase Date'])

claim_cleaned_df['Failure Date'] = pd.to_datetime(claim_cleaned_df['Failure Date'])

claim_cleaned_df['Repair Date'] = pd.to_datetime(claim_cleaned_df['Repair Date'])

# Calculate the number of days of usage
claim_cleaned_df['Days of Usage'] = (claim_cleaned_df['Failure Date'] - claim_cleaned_df['Purchase Date']).dt.days

# Print the first few rows to verify the results
print(claim_cleaned_df.head())

   Claim Number Model Number    Warranty Item Description Serial Number  \
0      71692559  55RK6HNR050  MOWER:CWB:36 HYD2800 RECOIL   1B198H70003
1      71698531  55RK6HNR050  MOWER:CWB:36 HYD2800 RECOIL   1B198H70003
2      71700308  55RK6HNR050  MOWER:CWB:36 HYD2800 RECOIL   1B198H70003
3      71707104  55RK6HNR050  MOWER:CWB:36 HYD2800 RECOIL   1B198H70003
4      71726990  55RK6HNR050  MOWER:CWB:36 HYD2800 RECOIL   1B158H70028

   Engine Model Transmission Model Repair Dealer Number Owner City  \
0  752SFS481S33          618-07347               S76489    ANDOVER
1  752SFS481S33          618-07347               S76489    ANDOVER
2  752SFS481S33          618-07347               S76489    ANDOVER
3  752SFS481S33          618-07347               S76489    ANDOVER
4  752SFS481S33          618-07347               S77690       APEX

  Owner State Owner Zip Purchase Date Failure Date Repair Date  Hours Used  \
0          KS     67002    2019-07-13   2020-07-18  2020-07-18       431.1
1          KS     67002    2019-07-13   2020-07-18  2020-08-01       431.1
2          KS     67002    2019-07-13   2020-07-18  2020-08-01       431.1
3          KS     67002    2019-07-13   2020-09-26  2020-09-26       450.0
4          NC     27502    2020-05-01   2020-06-24  2021-02-01         0.0

  Posted Calendar Month Name Abbr  Total Claim Dollars  Days of Usage
0                         2020-08                98.86          371.0
1                         2020-09                27.98          371.0
2                         2020-09               183.94          371.0
3                         2020-10                69.50          441.0
4                         2021-02               169.26           54.0

## 2. Failure Season

When we checked the data, we have identified the data consists of three countries USA, Canada, Australia. In this step, we will be extracting the Failure Season based on Failure Date and the hemisphere the country lies in.

AUSTRALIA lies in southern hemisphere

USA and CANADA Lies in Nothern Hemisphere

In [9]:
import pandas as pd
import pytz

# Time Zone Mapping (Expanded)
timezone_map = {
    'KS': 'US/Central', 'NC': 'US/Eastern', 'MS': 'US/Central', 'WA': 'US/Pacific',
    'TN': 'US/Central', 'TX': 'US/Central', 'WI': 'US/Central', 'OH': 'US/Eastern',
    'MI': 'US/Eastern', 'GA': 'US/Eastern', 'VA': 'US/Eastern', 'KY': 'US/Eastern',
    'PA': 'US/Eastern', 'WV': 'US/Eastern', 'MO': 'US/Central', 'ID': 'US/Mountain',
    'NE': 'US/Central', 'QC': 'Canada/Eastern', 'NY': 'US/Eastern', 'MN': 'US/Central',
    'OR': 'US/Pacific', 'ON': 'Canada/Eastern', 'IL': 'US/Central', 'IN': 'US/Eastern',
    'MD': 'US/Eastern', 'NJ': 'US/Eastern', 'IA': 'US/Central', 'NH': 'US/Eastern',
    'AL': 'US/Central', 'SC': 'US/Eastern', 'CT': 'US/Eastern', 'FL': 'US/Eastern',
    'OK': 'US/Central', 'LA': 'US/Central', 'AR': 'US/Central', 'DE': 'US/Eastern',
    'AB': 'Canada/Mountain', 'NB': 'Canada/Atlantic', 'SK': 'Canada/Central',
    'MA': 'US/Eastern', 'ME': 'US/Eastern', 'ND': 'US/Central', 'MB': 'Canada/Central',
    'VT': 'US/Eastern', 'SD': 'US/Central', 'RI': 'US/Eastern', 'BC': 'Canada/Pacific',
    'CO': 'US/Mountain', 'NS': 'Canada/Atlantic', 'PE': 'Canada/Atlantic',
    'VI': 'Australia/Victoria', 'TS': 'Australia/Tasmania', 'HI': 'US/Hawaii',
    'AK': 'US/Alaska', 'CA': 'US/Pacific', 'WY': 'US/Mountain', 'MT': 'US/Mountain',
    'AZ': 'US/Mountain', 'UT': 'US/Mountain', 'SA': 'Australia/South',
    'QL': 'Australia/Queensland', 'AC': 'Australia/Sydney', 'NV': 'US/Pacific',
    'NT': 'Australia/Darwin', 'NM': 'US/Mountain', 'DC': 'US/Eastern',
    'NL': 'Canada/Newfoundland', 'YT': 'Canada/Pacific', 'GU': 'Pacific/Guam',
    'NU': 'Canada/Central'
}

# Hemisphere Mapping (Expanded)
hemisphere_map = {
    'KS': 'Northern', 'NC': 'Northern', 'MS': 'Northern', 'WA': 'Northern',
    'TN': 'Northern', 'TX': 'Northern', 'WI': 'Northern', 'OH': 'Northern',
    'MI': 'Northern', 'GA': 'Northern', 'VA': 'Northern', 'KY': 'Northern',
    'PA': 'Northern', 'WV': 'Northern', 'MO': 'Northern', 'ID': 'Northern',
    'NE': 'Northern', 'QC': 'Northern', 'NY': 'Northern', 'MN': 'Northern',
    'OR': 'Northern', 'ON': 'Northern', 'IL': 'Northern', 'IN': 'Northern',
    'MD': 'Northern', 'NJ': 'Northern', 'IA': 'Northern', 'NH': 'Northern',
    'AL': 'Northern', 'SC': 'Northern', 'CT': 'Northern', 'FL': 'Northern',
    'OK': 'Northern', 'LA': 'Northern', 'AR': 'Northern', 'DE': 'Northern',
    'AB': 'Northern', 'NB': 'Northern', 'SK': 'Northern', 'MA': 'Northern',
    'ME': 'Northern', 'ND': 'Northern', 'MB': 'Northern', 'VT': 'Northern',
    'SD': 'Northern', 'RI': 'Northern', 'BC': 'Northern', 'CO': 'Northern',
    'NS': 'Northern', 'PE': 'Northern', 'VI': 'Southern', 'TS': 'Southern',
    'HI': 'Northern', 'AK': 'Northern', 'CA': 'Northern', 'WY': 'Northern',
    'MT': 'Northern', 'AZ': 'Northern', 'UT': 'Northern', 'SA': 'Southern',
    'QL': 'Southern', 'AC': 'Southern', 'NV': 'Northern', 'NT': 'Southern',
    'NM': 'Northern', 'DC': 'Northern', 'NL': 'Northern', 'YT': 'Northern',
    'GU': 'Northern', 'NU': 'Northern'
}

def get_season(month):
    if month in [6, 7, 8]:
        return 'Summer'
    elif month in [9, 10, 11]:
        return 'Autumn'
    elif month in [12, 1, 2]:
        return 'Winter'
    else:
        return 'Spring'

def get_local_month(row):
    date = row['Failure Date']
    state = row['Owner State']
    if pd.isna(date) or pd.isna(state):
        return None
    try:
        tz_str = timezone_map[state]
        tz = pytz.timezone(tz_str)
        local_date = date.tz_convert(tz) if date.tzinfo else date.tz_localize('UTC').tz_convert(tz)
        return local_date.month
    except KeyError:
        print(f"Timezone not found for state: {state}")
        return None

def get_adjusted_season(row):
    month = row['Local Failure Month']
    state = row['Owner State']
    hemisphere = hemisphere_map.get(state)

    if month is None or hemisphere is None:
        return None

    if hemisphere == 'Northern':
        return get_season(month)
    else:
        if month in [12, 1, 2]:
            return 'Summer'
        elif month in [3, 4, 5]:
            return 'Autumn'
        elif month in [6, 7, 8]:
            return 'Winter'
        else:
            return 'Spring'

# Apply the functions to create the 'failure Season' column
claim_cleaned_df['Local Failure Month'] = claim_cleaned_df.apply(get_local_month, axis=1)
claim_cleaned_df['Failure Season'] = claim_cleaned_df.apply(get_adjusted_season, axis=1)

# Drop the Local Failure Month
claim_cleaned_df.drop(columns=['Local Failure Month'], inplace=True)

# Print the first few rows
print(claim_cleaned_df.head())

   Claim Number Model Number    Warranty Item Description Serial Number  \
0      71692559  55RK6HNR050  MOWER:CWB:36 HYD2800 RECOIL   1B198H70003
1      71698531  55RK6HNR050  MOWER:CWB:36 HYD2800 RECOIL   1B198H70003
2      71700308  55RK6HNR050  MOWER:CWB:36 HYD2800 RECOIL   1B198H70003
3      71707104  55RK6HNR050  MOWER:CWB:36 HYD2800 RECOIL   1B198H70003
4      71726990  55RK6HNR050  MOWER:CWB:36 HYD2800 RECOIL   1B158H70028

   Engine Model Transmission Model Repair Dealer Number Owner City  \
0  752SFS481S33          618-07347               S76489    ANDOVER
1  752SFS481S33          618-07347               S76489    ANDOVER
2  752SFS481S33          618-07347               S76489    ANDOVER
3  752SFS481S33          618-07347               S76489    ANDOVER
4  752SFS481S33          618-07347               S77690       APEX

  Owner State Owner Zip Purchase Date Failure Date Repair Date  Hours Used  \
0          KS     67002    2019-07-13   2020-07-18  2020-07-18       431.1
1          KS     67002    2019-07-13   2020-07-18  2020-08-01       431.1
2          KS     67002    2019-07-13   2020-07-18  2020-08-01       431.1
3          KS     67002    2019-07-13   2020-09-26  2020-09-26       450.0
4          NC     27502    2020-05-01   2020-06-24  2021-02-01         0.0

  Posted Calendar Month Name Abbr  Total Claim Dollars  Days of Usage  \
0                         2020-08                98.86          371.0
1                         2020-09                27.98          371.0
2                         2020-09               183.94          371.0
3                         2020-10                69.50          441.0
4                         2021-02               169.26           54.0

  Failure Season
0         Summer
1         Summer
2         Summer
3         Autumn
4         Summer

In [10]:
# check info again
claim_cleaned_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375364 entries, 0 to 375363
Data columns (total 18 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Claim Number                     375364 non-null  int64
 1   Model Number                     375348 non-null  object
 2   Warranty Item Description        375364 non-null  object
 3   Serial Number                    374033 non-null  object
 4   Engine Model                     333224 non-null  object
 5   Transmission Model               277260 non-null  object
 6   Repair Dealer Number             368636 non-null  object
 7   Owner City                       305478 non-null  object
 8   Owner State                      305381 non-null  object
 9   Owner Zip                        305481 non-null  object
 10  Purchase Date                    375349 non-null  datetime64[ns]
 11  Failure Date                     375362 non-null  datetime64[ns]
 12  Repair Date                      375364 non-null  datetime64[ns]
 13  Hours Used                       375364 non-null  float64
 14  Posted Calendar Month Name Abbr  375364 non-null  object
 15  Total Claim Dollars              375364 non-null  float64
 16  Days of Usage                    375349 non-null  float64
 17  Failure Season                   305381 non-null  object
dtypes: datetime64[ns](3), float64(3), int64(1), object(11)
memory usage: 51.5+ MB

## Text Mining on Textual Columns

In [11]:
# Import necessary libraries

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
import re

In [12]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [14]:
# Download NLTK resources
nltk.download('punkt')  # For tokenization
nltk.download('stopwords')
nltk.download('wordnet')  # For lemmatization

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [15]:
# Text Preprocessing: Defining Components
# removal of stop words
stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()

In [16]:
# Text Preprocessing: Tokenization, Stemming, Stopword Removal, and Cleaning

def preprocess_text(text):
    # convert all the letters to Lowercasing
    text = text.lower()
    print(f"\nAfter Lowercasing: '{text}'")

    # Removing Punctuation and Special Characters from the text
    text = re.sub(r'[^\w\s]', '', text)
    print(f"After Punctuation Removal: '{text}'")

    # Tokenization - Splitting the text into Words (tokens)
    tokens = nltk.word_tokenize(text)
    print(f"After Tokenization: {tokens}")

    # Stopword Removal and Stemming
    cleaned_tokens = []
    for word in tokens:
        if word not in stop_words:
            stemmed_word = stemmer.stem(word)
            cleaned_tokens.append(stemmed_word)
    print(f"After Stopword Removal and Stemming: {cleaned_tokens}")

    # Joining Tokens Back into a String
    return ' '.join(cleaned_tokens)

In [17]:
# Applying Text Preprocessing on failure part data columns Failure Part Description Cleaned, Complaint Diagnosis_Cleaned, Work Performed_Cleaned

failure_part_cleaned_df['Failure Part Description Cleaned'] = failure_part_cleaned_df['Failure Part Description'].apply(preprocess_text)
failure_part_cleaned_df['Work Performed_Cleaned'] = failure_part_cleaned_df['Work Performed'].apply(preprocess_text)
failure_part_cleaned_df['Complaint Diagnosis_Cleaned'] = failure_part_cleaned_df['Complaint Diagnosis'].apply(preprocess_text)

Streaming output truncated to the last 5000 lines.

After Lowercasing: 'inspection pr -livraison'
After Punctuation Removal: 'inspection pr livraison'
After Tokenization: ['inspection', 'pr', 'livraison']
After Stopword Removal and Stemming: ['inspect', 'pr', 'livraison']

After Lowercasing: 'inspection pr -livraison'
After Punctuation Removal: 'inspection pr livraison'
After Tokenization: ['inspection', 'pr', 'livraison']
After Stopword Removal and Stemming: ['inspect', 'pr', 'livraison']

After Lowercasing: 'no compression - case# 06104957 tech found pieces of the cylinder wall on top of the piston and the oil scraper rings were in the crankcase due to a machining defect on the cylinder wall. when the rings were pulled off due t o the machining defect it caus ed damage to the crankcase and cylinder wall. unit will need clyinder, cran kcase, crankshaft, connecting rod, piston and piston rings. cost of repairs far exceed cost of new unit. going to replace unit for customer'
After Punctuation Removal: 'no compression  case 06104957 tech found pieces of the cylinder wall on top of the piston and the oil scraper rings were in the crankcase due to a machining defect on the cylinder wall when the rings were pulled off due t o the machining defect it caus ed damage to the crankcase and cylinder wall unit will need clyinder cran kcase crankshaft connecting rod piston and piston rings cost of repairs far exceed cost of new unit going to replace unit for customer'
After Tokenization: ['no', 'compression', 'case', '06104957', 'tech', 'found', 'pieces', 'of', 'the', 'cylinder', 'wall', 'on', 'top', 'of', 'the', 'piston', 'and', 'the', 'oil', 'scraper', 'rings', 'were', 'in', 'the', 'crankcase', 'due', 'to', 'a', 'machining', 'defect', 'on', 'the', 'cylinder', 'wall', 'when', 'the', 'rings', 'were', 'pulled', 'off', 'due', 't', 'o', 'the', 'machining', 'defect', 'it', 'caus', 'ed', 'damage', 'to', 'the', 'crankcase', 'and', 'cylinder', 'wall', 'unit', 'will', 'need', 'clyinder', 'cran', 'kcase', 'crankshaft', 'connecting', 'rod', 'piston', 'and', 'piston', 'rings', 'cost', 'of', 'repairs', 'far', 'exceed', 'cost', 'of', 'new', 'unit', 'going', 'to', 'replace', 'unit', 'for', 'customer']
After Stopword Removal and Stemming: ['compress', 'case', '06104957', 'tech', 'found', 'piec', 'cylind', 'wall', 'top', 'piston', 'oil', 'scraper', 'ring', 'crankcas', 'due', 'machin', 'defect', 'cylind', 'wall', 'ring', 'pull', 'due', 'machin', 'defect', 'cau', 'ed', 'damag', 'crankcas', 'cylind', 'wall', 'unit', 'need', 'clyinder', 'cran', 'kcase', 'crankshaft', 'connect', 'rod', 'piston', 'piston', 'ring', 'cost', 'repair', 'far', 'exceed', 'cost', 'new', 'unit', 'go', 'replac', 'unit', 'custom']

After Lowercasing: 'right side deck spindle assembly failed. appears the top pulley nut came lo ose and everything got loose and worn. replaced spindle assembly'
After Punctuation Removal: 'right side deck spindle assembly failed appears the top pulley nut came lo ose and everything got loose and worn replaced spindle assembly'
After Tokenization: ['right', 'side', 'deck', 'spindle', 'assembly', 'failed', 'appears', 'the', 'top', 'pulley', 'nut', 'came', 'lo', 'ose', 'and', 'everything', 'got', 'loose', 'and', 'worn', 'replaced', 'spindle', 'assembly']
After Stopword Removal and Stemming: ['right', 'side', 'deck', 'spindl', 'assembl', 'fail', 'appear', 'top', 'pulley', 'nut', 'came', 'lo', 'ose', 'everyth', 'got', 'loos', 'worn', 'replac', 'spindl', 'assembl']

After Lowercasing: ''
After Punctuation Removal: ''
After Tokenization: []
After Stopword Removal and Stemming: []

After Lowercasing: 'pdi'
After Punctuation Removal: 'pdi'
After Tokenization: ['pdi']
After Stopword Removal and Stemming: ['pdi']

After Lowercasing: 'muffler exhaust pipe has broken at weld where pipe and muffler meet. remove d and replaced muffler with template kit. case # 06114616'
After Punctuation Removal: 'muffler exhaust pipe has broken at weld where pipe and muffler meet remove d and replaced muffler with template kit case  06114616'
After Tokenization: ['muffler', 'exhaust', 'pipe', 'has', 'broken', 'at', 'weld', 'where', 'pipe', 'and', 'muffler', 'meet', 'remove', 'd', 'and', 'replaced', 'muffler', 'with', 'template', 'kit', 'case', '06114616']
After Stopword Removal and Stemming: ['muffler', 'exhaust', 'pipe', 'broken', 'weld', 'pipe', 'muffler', 'meet', 'remov', 'replac', 'muffler', 'templat', 'kit', 'case', '06114616']

After Lowercasing: ''
After Punctuation Removal: ''
After Tokenization: []
After Stopword Removal and Stemming: []

After Lowercasing: 'pdi/dealer prep'
After Punctuation Removal: 'pdidealer prep'
After Tokenization: ['pdidealer', 'prep']
After Stopword Removal and Stemming: ['pdideal', 'prep']

After Lowercasing: 'did pdi as required'
After Punctuation Removal: 'did pdi as required'
After Tokenization: ['did', 'pdi', 'as', 'required']
After Stopword Removal and Stemming: ['pdi', 'requir']

After Lowercasing: 'checked deck and found spindle was bad. pulley had come loose on the spindl on. one of the bolts needed to be drilled out. drilled out broken bolt. in stalled new hardware. installe d new spindle, re installed blades.'
After Punctuation Removal: 'checked deck and found spindle was bad pulley had come loose on the spindl on one of the bolts needed to be drilled out drilled out broken bolt in stalled new hardware installe d new spindle re installed blades'
After Tokenization: ['checked', 'deck', 'and', 'found', 'spindle', 'was', 'bad', 'pulley', 'had', 'come', 'loose', 'on', 'the', 'spindl', 'on', 'one', 'of', 'the', 'bolts', 'needed', 'to', 'be', 'drilled', 'out', 'drilled', 'out', 'broken', 'bolt', 'in', 'stalled', 'new', 'hardware', 'installe', 'd', 'new', 'spindle', 're', 'installed', 'blades']
After Stopword Removal and Stemming: ['check', 'deck', 'found', 'spindl', 'bad', 'pulley', 'come', 'loos', 'spindl', 'one', 'bolt', 'need', 'drill', 'drill', 'broken', 'bolt', 'stall', 'new', 'hardwar', 'instal', 'new', 'spindl', 'instal', 'blade']

After Lowercasing: ''
After Punctuation Removal: ''
After Tokenization: []
After Stopword Removal and Stemming: []

After Lowercasing: 'pdi'
After Punctuation Removal: 'pdi'
After Tokenization: ['pdi']
After Stopword Removal and Stemming: ['pdi']

After Lowercasing: 'moteur tres bruyant, boucane, boulons de l echappement qui etait mal instal l  a l usine et a endommag  le systeme d echappement; changer echappement'
After Punctuation Removal: 'moteur tres bruyant boucane boulons de l echappement qui etait mal instal l  a l usine et a endommag  le systeme d echappement changer echappement'
After Tokenization: ['moteur', 'tres', 'bruyant', 'boucane', 'boulons', 'de', 'l', 'echappement', 'qui', 'etait', 'mal', 'instal', 'l', 'a', 'l', 'usine', 'et', 'a', 'endommag', 'le', 'systeme', 'd', 'echappement', 'changer', 'echappement']
After Stopword Removal and Stemming: ['moteur', 'tre', 'bruyant', 'boucan', 'boulon', 'de', 'l', 'echapp', 'qui', 'etait', 'mal', 'instal', 'l', 'l', 'usin', 'et', 'endommag', 'le', 'system', 'echapp', 'changer', 'echapp']

After Lowercasing: 'la courroie d barquait.'
After Punctuation Removal: 'la courroie d barquait'
After Tokenization: ['la', 'courroie', 'd', 'barquait']
After Stopword Removal and Stemming: ['la', 'courroi', 'barquait']

After Lowercasing: 'cable cass ,changer cable'
After Punctuation Removal: 'cable cass changer cable'
After Tokenization: ['cable', 'cass', 'changer', 'cable']
After Stopword Removal and Stemming: ['cabl', 'cass', 'changer', 'cabl']

After Lowercasing: 'le tracteur ne veut pas demarrer. tester et verifier batterie. la batterie ne tient pas sa charge.'
After Punctuation Removal: 'le tracteur ne veut pas demarrer tester et verifier batterie la batterie ne tient pas sa charge'
After Tokenization: ['le', 'tracteur', 'ne', 'veut', 'pas', 'demarrer', 'tester', 'et', 'verifier', 'batterie', 'la', 'batterie', 'ne', 'tient', 'pas', 'sa', 'charge']
After Stopword Removal and Stemming: ['le', 'tracteur', 'ne', 'veut', 'pa', 'demarr', 'tester', 'et', 'verifi', 'batteri', 'la', 'batteri', 'ne', 'tient', 'pa', 'sa', 'charg']

After Lowercasing: 'as per conversation with dominic moores. hydro drives would struggle to dri ve once up to temperature. new hydro units sent at no charge to replace.'
After Punctuation Removal: 'as per conversation with dominic moores hydro drives would struggle to dri ve once up to temperature new hydro units sent at no charge to replace'
After Tokenization: ['as', 'per', 'conversation', 'with', 'dominic', 'moores', 'hydro', 'drives', 'would', 'struggle', 'to', 'dri', 've', 'once', 'up', 'to', 'temperature', 'new', 'hydro', 'units', 'sent', 'at', 'no', 'charge', 'to', 'replace']
After Stopword Removal and Stemming: ['per', 'convers', 'domin', 'moor', 'hydro', 'drive', 'would', 'struggl', 'dri', 'temperatur', 'new', 'hydro', 'unit', 'sent', 'charg', 'replac']

After Lowercasing: 'battery was dead when he got the machine home to use'
After Punctuation Removal: 'battery was dead when he got the machine home to use'
After Tokenization: ['battery', 'was', 'dead', 'when', 'he', 'got', 'the', 'machine', 'home', 'to', 'use']
After Stopword Removal and Stemming: ['batteri', 'dead', 'got', 'machin', 'home', 'use']

After Lowercasing: ''
After Punctuation Removal: ''
After Tokenization: []
After Stopword Removal and Stemming: []

After Lowercasing: 'bent axle'
After Punctuation Removal: 'bent axle'
After Tokenization: ['bent', 'axle']
After Stopword Removal and Stemming: ['bent', 'axl']

After Lowercasing: 'harg  et test , le voltage ne monte pas plus que 9.4v.'
After Punctuation Removal: 'harg  et test  le voltage ne monte pas plus que 94v'
After Tokenization: ['harg', 'et', 'test', 'le', 'voltage', 'ne', 'monte', 'pas', 'plus', 'que', '94v']
After Stopword Removal and Stemming: ['harg', 'et', 'test', 'le', 'voltag', 'ne', 'mont', 'pa', 'plu', 'que', '94v']

After Lowercasing: 'customer recently purchased tractor from rona. would not start. battery w'
After Punctuation Removal: 'customer recently purchased tractor from rona would not start battery w'
After Tokenization: ['customer', 'recently', 'purchased', 'tractor', 'from', 'rona', 'would', 'not', 'start', 'battery', 'w']
After Stopword Removal and Stemming: ['custom', 'recent', 'purchas', 'tractor', 'rona', 'would', 'start', 'batteri', 'w']

After Lowercasing: 'pto clutch holder bracket broke and pto clutch spun ripping out wiring'
After Punctuation Removal: 'pto clutch holder bracket broke and pto clutch spun ripping out wiring'
After Tokenization: ['pto', 'clutch', 'holder', 'bracket', 'broke', 'and', 'pto', 'clutch', 'spun', 'ripping', 'out', 'wiring']
After Stopword Removal and Stemming: ['pto', 'clutch', 'holder', 'bracket', 'broke', 'pto', 'clutch', 'spun', 'rip', 'wire']

After Lowercasing: ''
After Punctuation Removal: ''
After Tokenization: []
After Stopword Removal and Stemming: []

After Lowercasing: 'deck idler pulley bearing seised'
After Punctuation Removal: 'deck idler pulley bearing seised'
After Tokenization: ['deck', 'idler', 'pulley', 'bearing', 'seised']
After Stopword Removal and Stemming: ['deck', 'idler', 'pulley', 'bear', 'seis']

After Lowercasing: 'pdi'
After Punctuation Removal: 'pdi'
After Tokenization: ['pdi']
After Stopword Removal and Stemming: ['pdi']

After Lowercasing: 'uint deemed unrepairable motor needs to be replaced becasue of the ca'
After Punctuation Removal: 'uint deemed unrepairable motor needs to be replaced becasue of the ca'
After Tokenization: ['uint', 'deemed', 'unrepairable', 'motor', 'needs', 'to', 'be', 'replaced', 'becasue', 'of', 'the', 'ca']
After Stopword Removal and Stemming: ['uint', 'deem', 'unrepair', 'motor', 'need', 'replac', 'becasu', 'ca']

After Lowercasing: 'button failure on level'
After Punctuation Removal: 'button failure on level'
After Tokenization: ['button', 'failure', 'on', 'level']
After Stopword Removal and Stemming: ['button', 'failur', 'level']

After Lowercasing: 't claim.'
After Punctuation Removal: 't claim'
After Tokenization: ['t', 'claim']
After Stopword Removal and Stemming: ['claim']

After Lowercasing: 'case 09844461. mtd tech line advised that there was a manufacturing issue a t the time of this production. possibly the bearing race not installed prop erly. cause complete transmission failure. i did the best i could to read t he model and serial number off the transmission. i attached photos as well.'
After Punctuation Removal: 'case 09844461 mtd tech line advised that there was a manufacturing issue a t the time of this production possibly the bearing race not installed prop erly cause complete transmission failure i did the best i could to read t he model and serial number off the transmission i attached photos as well'
After Tokenization: ['case', '09844461', 'mtd', 'tech', 'line', 'advised', 'that', 'there', 'was', 'a', 'manufacturing', 'issue', 'a', 't', 'the', 'time', 'of', 'this', 'production', 'possibly', 'the', 'bearing', 'race', 'not', 'installed', 'prop', 'erly', 'cause', 'complete', 'transmission', 'failure', 'i', 'did', 'the', 'best', 'i', 'could', 'to', 'read', 't', 'he', 'model', 'and', 'serial', 'number', 'off', 'the', 'transmission', 'i', 'attached', 'photos', 'as', 'well']
After Stopword Removal and Stemming: ['case', '09844461', 'mtd', 'tech', 'line', 'advis', 'manufactur', 'issu', 'time', 'product', 'possibl', 'bear', 'race', 'instal', 'prop', 'erli', 'caus', 'complet', 'transmiss', 'failur', 'best', 'could', 'read', 'model', 'serial', 'number', 'transmiss', 'attach', 'photo', 'well']

After Lowercasing: '09804925 )'
After Punctuation Removal: '09804925 '
After Tokenization: ['09804925']
After Stopword Removal and Stemming: ['09804925']

After Lowercasing: 'la transmission glisse   haute et a basse vitesse'
After Punctuation Removal: 'la transmission glisse   haute et a basse vitesse'
After Tokenization: ['la', 'transmission', 'glisse', 'haute', 'et', 'a', 'basse', 'vitesse']
After Stopword Removal and Stemming: ['la', 'transmiss', 'gliss', 'haut', 'et', 'bass', 'vitess']

After Lowercasing: ',batterie tien pas sa charge'
After Punctuation Removal: 'batterie tien pas sa charge'
After Tokenization: ['batterie', 'tien', 'pas', 'sa', 'charge']
After Stopword Removal and Stemming: ['batteri', 'tien', 'pa', 'sa', 'charg']

After Lowercasing: 'starter soleniod internal failure.. used stens part as replacement. cost 12.34 plus 20%'
After Punctuation Removal: 'starter soleniod internal failure used stens part as replacement cost 1234 plus 20'
After Tokenization: ['starter', 'soleniod', 'internal', 'failure', 'used', 'stens', 'part', 'as', 'replacement', 'cost', '1234', 'plus', '20']
After Stopword Removal and Stemming: ['starter', 'soleniod', 'intern', 'failur', 'use', 'sten', 'part', 'replac', 'cost', '1234', 'plu', '20']

After Lowercasing: 'le moteur de la souffleuse tourne par coup sur le ralenti. le idle jet est bouch'
After Punctuation Removal: 'le moteur de la souffleuse tourne par coup sur le ralenti le idle jet est bouch'
After Tokenization: ['le', 'moteur', 'de', 'la', 'souffleuse', 'tourne', 'par', 'coup', 'sur', 'le', 'ralenti', 'le', 'idle', 'jet', 'est', 'bouch']
After Stopword Removal and Stemming: ['le', 'moteur', 'de', 'la', 'souffleus', 'tourn', 'par', 'coup', 'sur', 'le', 'ralenti', 'le', 'idl', 'jet', 'est', 'bouch']

After Lowercasing: ''
After Punctuation Removal: ''
After Tokenization: []
After Stopword Removal and Stemming: []

After Lowercasing: 'failure: unit will not start too costly to repair - consumer reimbursement'
After Punctuation Removal: 'failure unit will not start too costly to repair  consumer reimbursement'
After Tokenization: ['failure', 'unit', 'will', 'not', 'start', 'too', 'costly', 'to', 'repair', 'consumer', 'reimbursement']
After Stopword Removal and Stemming: ['failur', 'unit', 'start', 'costli', 'repair', 'consum', 'reimburs']

After Lowercasing: 'this claim is for the labour on case #09742621. we replaced the transmissio'
After Punctuation Removal: 'this claim is for the labour on case 09742621 we replaced the transmissio'
After Tokenization: ['this', 'claim', 'is', 'for', 'the', 'labour', 'on', 'case', '09742621', 'we', 'replaced', 'the', 'transmissio']
After Stopword Removal and Stemming: ['claim', 'labour', 'case', '09742621', 'replac', 'transmissio']

After Lowercasing: 'pdi 25$'
After Punctuation Removal: 'pdi 25'
After Tokenization: ['pdi', '25']
After Stopword Removal and Stemming: ['pdi', '25']

After Lowercasing: 'meme temps'
After Punctuation Removal: 'meme temps'
After Tokenization: ['meme', 'temps']
After Stopword Removal and Stemming: ['meme', 'temp']

After Lowercasing: 'spindles are very loud removed all three spindles and found the bearings were very rough r+r all three spindles invoice # 806550'
After Punctuation Removal: 'spindles are very loud removed all three spindles and found the bearings were very rough rr all three spindles invoice  806550'
After Tokenization: ['spindles', 'are', 'very', 'loud', 'removed', 'all', 'three', 'spindles', 'and', 'found', 'the', 'bearings', 'were', 'very', 'rough', 'rr', 'all', 'three', 'spindles', 'invoice', '806550']
After Stopword Removal and Stemming: ['spindl', 'loud', 'remov', 'three', 'spindl', 'found', 'bear', 'rough', 'rr', 'three', 'spindl', 'invoic', '806550']

After Lowercasing: 'pdi'
After Punctuation Removal: 'pdi'
After Tokenization: ['pdi']
After Stopword Removal and Stemming: ['pdi']

After Lowercasing: 'faulty battery'
After Punctuation Removal: 'faulty battery'
After Tokenization: ['faulty', 'battery']
After Stopword Removal and Stemming: ['faulti', 'batteri']

After Lowercasing: 'faulty battery'
After Punctuation Removal: 'faulty battery'
After Tokenization: ['faulty', 'battery']
After Stopword Removal and Stemming: ['faulti', 'batteri']

After Lowercasing: 'inspection pre-livraison'
After Punctuation Removal: 'inspection prelivraison'
After Tokenization: ['inspection', 'prelivraison']
After Stopword Removal and Stemming: ['inspect', 'prelivraison']

After Lowercasing: ''
After Punctuation Removal: ''
After Tokenization: []
After Stopword Removal and Stemming: []

After Lowercasing: 'inspection pre-livraison'
After Punctuation Removal: 'inspection prelivraison'
After Tokenization: ['inspection', 'prelivraison']
After Stopword Removal and Stemming: ['inspect', 'prelivraison']

After Lowercasing: 'inspection pre-livraison'
After Punctuation Removal: 'inspection prelivraison'
After Tokenization: ['inspection', 'prelivraison']
After Stopword Removal and Stemming: ['inspect', 'prelivraison']

After Lowercasing: 'tracteur plus de traction'
After Punctuation Removal: 'tracteur plus de traction'
After Tokenization: ['tracteur', 'plus', 'de', 'traction']
After Stopword Removal and Stemming: ['tracteur', 'plu', 'de', 'traction']

After Lowercasing: 'carburetor is cracked and leaking fuel.'
After Punctuation Removal: 'carburetor is cracked and leaking fuel'
After Tokenization: ['carburetor', 'is', 'cracked', 'and', 'leaking', 'fuel']
After Stopword Removal and Stemming: ['carburetor', 'crack', 'leak', 'fuel']

After Lowercasing: 'inspection pre-livraison'
After Punctuation Removal: 'inspection prelivraison'
After Tokenization: ['inspection', 'prelivraison']
After Stopword Removal and Stemming: ['inspect', 'prelivraison']

After Lowercasing: 'inspection pre-livraison'
After Punctuation Removal: 'inspection prelivraison'
After Tokenization: ['inspection', 'prelivraison']
After Stopword Removal and Stemming: ['inspect', 'prelivraison']

After Lowercasing: 'inspection pre-livraison'
After Punctuation Removal: 'inspection prelivraison'
After Tokenization: ['inspection', 'prelivraison']
After Stopword Removal and Stemming: ['inspect', 'prelivraison']

After Lowercasing: 'inspection pre-livraison'
After Punctuation Removal: 'inspection prelivraison'
After Tokenization: ['inspection', 'prelivraison']
After Stopword Removal and Stemming: ['inspect', 'prelivraison']

After Lowercasing: ''

In [18]:
# apply TF-IDF Vectorization on Work Performed

tfidf_vectorizer_work = TfidfVectorizer(
    stop_words='english',  # Using built-in stop words for TF-IDF
    max_features=500,  # Limiting features
    ngram_range=(1, 2)  # Using unigrams and bigrams
)
work_tfidf_matrix = tfidf_vectorizer_work.fit_transform(failure_part_cleaned_df['Work Performed_Cleaned'])
work_tfidf_features_df = pd.DataFrame(work_tfidf_matrix.toarray(), columns=tfidf_vectorizer_work.get_feature_names_out())
print("\nWork Performed TF-IDF Features:")
print(work_tfidf_features_df.head())

Work Performed TF-IDF Features:
   1stage     2cycl  2stage  4cycl  75905924  75905924 servic  acid  \
0     0.0  0.000000     0.0    0.0       0.0              0.0   0.0
1     0.0  0.000000     0.0    0.0       0.0              0.0   0.0
2     0.0  0.000000     0.0    0.0       0.0              0.0   0.0
3     0.0  0.370657     0.0    0.0       0.0              0.0   0.0
4     0.0  0.000000     0.0    0.0       0.0              0.0   0.0

   acid charg   ad  adjust  ...  wheel  wheel assembl  wire  wire har  \
0         0.0  0.0     0.0  ...    0.0            0.0   0.0       0.0
1         0.0  0.0     0.0  ...    0.0            0.0   0.0       0.0
2         0.0  0.0     0.0  ...    0.0            0.0   0.0       0.0
3         0.0  0.0     0.0  ...    0.0            0.0   0.0       0.0
4         0.0  0.0     0.0  ...    0.0            0.0   0.0       0.0

   wire harnesselectr  wire harnesstroubleshoot  wont      work  zone  \
0                 0.0                       0.0   0.0  0.000000   0.0
1                 0.0                       0.0   0.0  0.235378   0.0
2                 0.0                       0.0   0.0  0.000000   0.0
3                 0.0                       0.0   0.0  0.000000   0.0
4                 0.0                       0.0   0.0  0.000000   0.0

   zone start
0         0.0
1         0.0
2         0.0
3         0.0
4         0.0

[5 rows x 500 columns]

In [19]:
# TF-IDF Vectorization: Complaint Diagnosis

tfidf_vectorizer_diagnosis = TfidfVectorizer(
    stop_words='english',
    max_features=500,
    ngram_range=(1, 2)
)
diagnosis_tfidf_matrix = tfidf_vectorizer_diagnosis.fit_transform(failure_part_cleaned_df['Complaint Diagnosis_Cleaned'])
diagnosis_tfidf_features_df = pd.DataFrame(diagnosis_tfidf_matrix.toarray(), columns=tfidf_vectorizer_diagnosis.get_feature_names_out())
print("\nComplaint Diagnosis TF-IDF Features:")
print(diagnosis_tfidf_features_df.head())

Complaint Diagnosis TF-IDF Features:
   abl   ad  adjust  advis  advisori  air  allow  apart  area  arm  ...  wire  \
0  0.0  0.0     0.0    0.0       0.0  0.0    0.0    0.0   0.0  0.0  ...   0.0
1  0.0  0.0     0.0    0.0       0.0  0.0    0.0    0.0   0.0  0.0  ...   0.0
2  0.0  0.0     0.0    0.0       0.0  0.0    0.0    0.0   0.0  0.0  ...   0.0
3  0.0  0.0     0.0    0.0       0.0  0.0    0.0    0.0   0.0  0.0  ...   0.0
4  0.0  0.0     0.0    0.0       0.0  0.0    0.0    0.0   0.0  0.0  ...   0.0

   wire har  wobbl  wont  wont start  work  work properli  worn  wouldnt  \
0       0.0    0.0   0.0         0.0   0.0            0.0   0.0      0.0
1       0.0    0.0   0.0         0.0   0.0            0.0   0.0      0.0
2       0.0    0.0   0.0         0.0   0.0            0.0   0.0      0.0
3       0.0    0.0   0.0         0.0   0.0            0.0   0.0      0.0
4       0.0    0.0   0.0         0.0   0.0            0.0   0.0      0.0

   wrong
0    0.0
1    0.0
2    0.0
3    0.0
4    0.0

[5 rows x 500 columns]

In [20]:
# TF-IDF Vectorization: Failure Part Description
tfidf_vectorizer_failure_part_descrip = TfidfVectorizer(
    stop_words='english',
    max_features=500,
    ngram_range=(1, 2)
)
failure_part_descrip_tfidf_matrix = tfidf_vectorizer_diagnosis.fit_transform(failure_part_cleaned_df['Failure Part Description Cleaned'])
failure_part_descrip_tfidf_features_df = pd.DataFrame(failure_part_descrip_tfidf_matrix.toarray(), columns=tfidf_vectorizer_diagnosis.get_feature_names_out())
print("\nFailure Part Description TF-IDF Features:")
print(failure_part_descrip_tfidf_features_df.head())

Failure Part Description TF-IDF Features:
   075  10275  1135  11ext   15  150  150 cca   17  175sd  175sd 272cc  ...  \
0  0.0    0.0   0.0    0.0  0.0  0.0      0.0  0.0    0.0          0.0  ...
1  0.0    0.0   0.0    0.0  0.0  0.0      0.0  0.0    0.0          0.0  ...
2  0.0    0.0   0.0    0.0  0.0  0.0      0.0  0.0    0.0          0.0  ...
3  0.0    0.0   0.0    0.0  0.0  0.0      0.0  0.0    0.0          0.0  ...
4  0.0    0.0   0.0    0.0  0.0  0.0      0.0  0.0    0.0          0.0  ...

   whl  whldrtrack  whook   wo  yel  yllw  ylw   zs   zt  zt sti
0  0.0         0.0    0.0  0.0  0.0   0.0  0.0  0.0  0.0     0.0
1  0.0         0.0    0.0  0.0  0.0   0.0  0.0  0.0  0.0     0.0
2  0.0         0.0    0.0  0.0  0.0   0.0  0.0  0.0  0.0     0.0
3  0.0         0.0    0.0  0.0  0.0   0.0  0.0  0.0  0.0     0.0
4  0.0         0.0    0.0  0.0  0.0   0.0  0.0  0.0  0.0     0.0

[5 rows x 500 columns]

In [21]:
# Calculating Row-Wise TF-IDF Sum

failure_part_cleaned_df['tfidf_work_sum'] = work_tfidf_features_df.sum(axis=1)

failure_part_cleaned_df['tfidf_diagnosis_sum'] = diagnosis_tfidf_features_df.sum(axis=1)

failure_part_cleaned_df['tfidf_failure_part_descrip_sum'] = failure_part_descrip_tfidf_features_df.sum(axis=1)

In [22]:
# check head again
failure_part_cleaned_df.head()

,Unnamed: 0,Failure Part id,Claim Number,Failure Description,Failure Part,Failure Part Description,Complaint Diagnosis,Work Performed,Vendor Number,Failure Part Description Cleaned,Work Performed_Cleaned,Complaint Diagnosis_Cleaned,tfidf_work_sum,tfidf_diagnosis_sum,tfidf_failure_part_descrip_sum
0,0,1,20028686,Loose,757-04083A,SEAT:3400:MED BACK:BLK NO OPS,guide inserts broken off seat,removed seat due to its sliding when customer ...,10403.0,seat3400m backblk op,remov seat due slide custom sit,guid insert broken seat,1.716939,1.697152,0.000000
1,1,2,20032406,Damaged at Factory,925-04347,SW:KEY:MOMENTARY,"TRACE FAULT, DEFECTIVE IGNITION SWITCH, REPLAC...","TRY TO KEY START UNIT WOULDNT TURN OVER, TRACE...",547628.0,swkeymomentari,tri key start unit wouldnt turn trace fault ig...,trace fault defect ignit switch replac make claim,3.599655,2.915857,0.000000
2,2,3,20032941,Will not Charge,925-1707D,BAT:U1:300 CCA DRY VENTED T UD,Faulty battery.,"Charged battery, tested faulty at 108CCA. Test...",725200.0,batu1300 cca dri vent ud,charg batteri test faulti 108cca test charg sy...,faulti batteri,2.868949,1.387277,2.995518
3,3,4,30843126,Cracked,753-06687,SHBLK:FC27CC:SC BLO,Found engine has a broken connecting rod. corr...,Cylinder/Piston Service (2cycle),0.0,shblkfc27ccsc blo,cylinderpiston servic 2cycl,found engin broken connect rod correct fuel us...,2.209310,3.199018,1.000000
4,4,5,20033818,Incorrect Part,951-12725,"CAP:FUEL:3.50"" ONEWAY VENT FKM",Fuel Cap recall,Replaced fuel caps to breathe correctly as per...,547628.0,capfuel350 oneway vent fkm,replac fuel cap breath correctli per recal,fuel cap recal,1.892130,1.718721,1.000000

In [23]:
failure_part_cleaned_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395279 entries, 0 to 395278
Data columns (total 15 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Unnamed: 0                        395279 non-null  int64
 1   Failure Part id                   395279 non-null  int64
 2   Claim Number                      395279 non-null  int64
 3   Failure Description               395279 non-null  object
 4   Failure Part                      395279 non-null  object
 5   Failure Part Description          395279 non-null  object
 6   Complaint Diagnosis               395279 non-null  object
 7   Work Performed                    395279 non-null  object
 8   Vendor Number                     394920 non-null  float64
 9   Failure Part Description Cleaned  395279 non-null  object
 10  Work Performed_Cleaned            395279 non-null  object
 11  Complaint Diagnosis_Cleaned       395279 non-null  object
 12  tfidf_work_sum                    395279 non-null  float64
 13  tfidf_diagnosis_sum               395279 non-null  float64
 14  tfidf_failure_part_descrip_sum    395279 non-null  float64
dtypes: float64(4), int64(3), object(8)
memory usage: 45.2+ MB

In [24]:
# now let's proceed with sentiment analysis for our Work Performed and Complaint Daignosis

# Install NLTK and Vader
!pip install nltk
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import pandas as pd

# Download required resources for NLTK
nltk.download('vader_lexicon')

# Initialize the sentiment analyzer
sid = SentimentIntensityAnalyzer()

Requirement already satisfied: nltk in /usr/local/lib/python3.11/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk) (8.1.8)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.11/dist-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from nltk) (4.67.1)

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...

In [25]:
from textblob import TextBlob
import pandas as pd

def get_sentiment(text):
    blob = TextBlob(text)
    return blob.sentiment.polarity


failure_part_cleaned_df['work_performed_sentiment'] = failure_part_cleaned_df['Work Performed'].apply(get_sentiment)
failure_part_cleaned_df['diagnosis_sentiment'] = failure_part_cleaned_df['Complaint Diagnosis'].apply(get_sentiment)

print(failure_part_cleaned_df[['work_performed_sentiment', 'diagnosis_sentiment']].head())

   work_performed_sentiment  diagnosis_sentiment
0                 -0.125000                 -0.4
1                  0.107008                  0.0
2                  0.500000                  0.0
3                  0.000000                 -0.4
4                  0.000000                  0.0

In [26]:
failure_part_cleaned_df.head()

,Unnamed: 0,Failure Part id,Claim Number,Failure Description,Failure Part,Failure Part Description,Complaint Diagnosis,Work Performed,Vendor Number,Failure Part Description Cleaned,Work Performed_Cleaned,Complaint Diagnosis_Cleaned,tfidf_work_sum,tfidf_diagnosis_sum,tfidf_failure_part_descrip_sum,work_performed_sentiment,diagnosis_sentiment
0,0,1,20028686,Loose,757-04083A,SEAT:3400:MED BACK:BLK NO OPS,guide inserts broken off seat,removed seat due to its sliding when customer ...,10403.0,seat3400m backblk op,remov seat due slide custom sit,guid insert broken seat,1.716939,1.697152,0.000000,-0.125000,-0.4
1,1,2,20032406,Damaged at Factory,925-04347,SW:KEY:MOMENTARY,"TRACE FAULT, DEFECTIVE IGNITION SWITCH, REPLAC...","TRY TO KEY START UNIT WOULDNT TURN OVER, TRACE...",547628.0,swkeymomentari,tri key start unit wouldnt turn trace fault ig...,trace fault defect ignit switch replac make claim,3.599655,2.915857,0.000000,0.107008,0.0
2,2,3,20032941,Will not Charge,925-1707D,BAT:U1:300 CCA DRY VENTED T UD,Faulty battery.,"Charged battery, tested faulty at 108CCA. Test...",725200.0,batu1300 cca dri vent ud,charg batteri test faulti 108cca test charg sy...,faulti batteri,2.868949,1.387277,2.995518,0.500000,0.0
3,3,4,30843126,Cracked,753-06687,SHBLK:FC27CC:SC BLO,Found engine has a broken connecting rod. corr...,Cylinder/Piston Service (2cycle),0.0,shblkfc27ccsc blo,cylinderpiston servic 2cycl,found engin broken connect rod correct fuel us...,2.209310,3.199018,1.000000,0.000000,-0.4
4,4,5,20033818,Incorrect Part,951-12725,"CAP:FUEL:3.50"" ONEWAY VENT FKM",Fuel Cap recall,Replaced fuel caps to breathe correctly as per...,547628.0,capfuel350 oneway vent fkm,replac fuel cap breath correctli per recal,fuel cap recal,1.892130,1.718721,1.000000,0.000000,0.0

In [27]:
import pandas as pd
import numpy as np

# Create a new column 'Failure Part Series' with the first three letters of each 'Failure Part'
failure_part_cleaned_df['Failure Part Series'] = failure_part_cleaned_df['Failure Part'].apply(lambda x: x[:3])

failure_part_cleaned_df.head()

,Unnamed: 0,Failure Part id,Claim Number,Failure Description,Failure Part,Failure Part Description,Complaint Diagnosis,Work Performed,Vendor Number,Failure Part Description Cleaned,Work Performed_Cleaned,Complaint Diagnosis_Cleaned,tfidf_work_sum,tfidf_diagnosis_sum,tfidf_failure_part_descrip_sum,work_performed_sentiment,diagnosis_sentiment,Failure Part Series
0,0,1,20028686,Loose,757-04083A,SEAT:3400:MED BACK:BLK NO OPS,guide inserts broken off seat,removed seat due to its sliding when customer ...,10403.0,seat3400m backblk op,remov seat due slide custom sit,guid insert broken seat,1.716939,1.697152,0.000000,-0.125000,-0.4,757
1,1,2,20032406,Damaged at Factory,925-04347,SW:KEY:MOMENTARY,"TRACE FAULT, DEFECTIVE IGNITION SWITCH, REPLAC...","TRY TO KEY START UNIT WOULDNT TURN OVER, TRACE...",547628.0,swkeymomentari,tri key start unit wouldnt turn trace fault ig...,trace fault defect ignit switch replac make claim,3.599655,2.915857,0.000000,0.107008,0.0,925
2,2,3,20032941,Will not Charge,925-1707D,BAT:U1:300 CCA DRY VENTED T UD,Faulty battery.,"Charged battery, tested faulty at 108CCA. Test...",725200.0,batu1300 cca dri vent ud,charg batteri test faulti 108cca test charg sy...,faulti batteri,2.868949,1.387277,2.995518,0.500000,0.0,925
3,3,4,30843126,Cracked,753-06687,SHBLK:FC27CC:SC BLO,Found engine has a broken connecting rod. corr...,Cylinder/Piston Service (2cycle),0.0,shblkfc27ccsc blo,cylinderpiston servic 2cycl,found engin broken connect rod correct fuel us...,2.209310,3.199018,1.000000,0.000000,-0.4,753
4,4,5,20033818,Incorrect Part,951-12725,"CAP:FUEL:3.50"" ONEWAY VENT FKM",Fuel Cap recall,Replaced fuel caps to breathe correctly as per...,547628.0,capfuel350 oneway vent fkm,replac fuel cap breath correctli per recal,fuel cap recal,1.892130,1.718721,1.000000,0.000000,0.0,951

In [28]:
# drop un wanted columns Unnamed: 0, Failure Part id, Failure Part Description	Complaint Diagnosis	Work Performed, Failure Part Description Cleaned, Work Performed_Cleaned, Complaint Diagnosis_Cleaned,
failure_part_cleaned_df.drop(columns=['Unnamed: 0', 'Failure Part Description', 'Complaint Diagnosis', 'Work Performed', 'Failure Part Description Cleaned', 'Work Performed_Cleaned', 'Complaint Diagnosis_Cleaned'], inplace=True)

In [29]:
# info
failure_part_cleaned_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395279 entries, 0 to 395278
Data columns (total 11 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Failure Part id                 395279 non-null  int64
 1   Claim Number                    395279 non-null  int64
 2   Failure Description             395279 non-null  object
 3   Failure Part                    395279 non-null  object
 4   Vendor Number                   394920 non-null  float64
 5   tfidf_work_sum                  395279 non-null  float64
 6   tfidf_diagnosis_sum             395279 non-null  float64
 7   tfidf_failure_part_descrip_sum  395279 non-null  float64
 8   work_performed_sentiment        395279 non-null  float64
 9   diagnosis_sentiment             395279 non-null  float64
 10  Failure Part Series             395279 non-null  object
dtypes: float64(6), int64(2), object(3)
memory usage: 33.2+ MB

In [30]:
# Aggregate failure part data on claim number

# since, we have 2 or more failure parts for some claim numbers, we are will be keeping the first occurence for those claim numbers.

failure_part_aggregated_df = failure_part_cleaned_df.groupby('Claim Number').agg({
    'Vendor Number': 'first',  # Keep the first occurrence of Vendor Number
    'Failure Part Series': 'first',  # Keep the first occurrence of Failure Part Series
    'tfidf_work_sum': 'sum',  # Sum of all tfidf_work_sum values
    'tfidf_diagnosis_sum': 'sum',  # Sum of all tfidf_diagnosis_sum values
    'tfidf_failure_part_descrip_sum': 'sum',  # Sum of all tfidf_failure_part_descrip_sum values
    'work_performed_sentiment': 'sum',  # Sum of all work_sentiment values
    'diagnosis_sentiment': 'sum',  # Sum of all diagnosis_sentiment values
    'Failure Description': 'first',  # Keep the first occurrence of Failure Description
    'Failure Part': 'count'  # Count of Failure Part ids
}).rename(columns={'Failure Part': 'Number of Failure Parts'}).reset_index()

In [31]:
# shape of aggregated dataframe
failure_part_aggregated_df.shape

(375364, 10)

In [32]:
# info
failure_part_aggregated_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375364 entries, 0 to 375363
Data columns (total 10 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Claim Number                    375364 non-null  int64
 1   Vendor Number                   375055 non-null  float64
 2   Failure Part Series             375364 non-null  object
 3   tfidf_work_sum                  375364 non-null  float64
 4   tfidf_diagnosis_sum             375364 non-null  float64
 5   tfidf_failure_part_descrip_sum  375364 non-null  float64
 6   work_performed_sentiment        375364 non-null  float64
 7   diagnosis_sentiment             375364 non-null  float64
 8   Failure Description             375364 non-null  object
 9   Number of Failure Parts         375364 non-null  int64
dtypes: float64(6), int64(2), object(2)
memory usage: 28.6+ MB

In [33]:
# Replacement part cleaned info
replacement_part_cleaned_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699993 entries, 0 to 699992
Data columns (total 11 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Unnamed: 0                    699993 non-null  int64
 1   Claim Number                  699993 non-null  int64
 2   Replacement Part id           699993 non-null  int64
 3   Replacement Part              699993 non-null  object
 4   Replacement Part Description  699993 non-null  object
 5   Part Quantity                 699993 non-null  int64
 6   Part Price                    699993 non-null  float64
 7   Part Extended Price           699993 non-null  float64
 8   Labor Rate                    699993 non-null  int64
 9   Paid Labor Hours              395279 non-null  float64
 10  Total Failure Cost            699992 non-null  float64
dtypes: float64(4), int64(5), object(2)
memory usage: 58.7+ MB

In [34]:
# aggregate replacement data on claim number

replacement_data_aggregated = replacement_part_cleaned_df.groupby('Claim Number').agg({
    'Replacement Part': 'count',  # Count of Replacement Part
    'Part Quantity': 'sum',  # Sum of Part Quantity
    'Part Extended Price': 'sum',  # Sum of Part Extended Price
    'Paid Labor Hours': 'sum' ,# Sum of Paid Labor Hours
    'Total Failure Cost': 'sum'
}).rename(columns={'Replacement Part': 'Number of Replacement Parts'}).reset_index()

In [35]:
# info
replacement_data_aggregated.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375364 entries, 0 to 375363
Data columns (total 6 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Claim Number                 375364 non-null  int64
 1   Number of Replacement Parts  375364 non-null  int64
 2   Part Quantity                375364 non-null  int64
 3   Part Extended Price          375364 non-null  float64
 4   Paid Labor Hours             375364 non-null  float64
 5   Total Failure Cost           375364 non-null  float64
dtypes: float64(3), int64(3)
memory usage: 17.2 MB

In [36]:
# merge failure_part_aggregated_df, replacement_data,aggregated, claim_cleaned_df
merged_claim_failure_replacement_df = pd.merge(failure_part_aggregated_df, replacement_data_aggregated, on='Claim Number', how='left')
merged_claim_failure_replacement_df = pd.merge(merged_claim_failure_replacement_df, claim_cleaned_df, on='Claim Number', how='left')

In [37]:
# info
merged_claim_failure_replacement_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375364 entries, 0 to 375363
Data columns (total 32 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Claim Number                     375364 non-null  int64
 1   Vendor Number                    375055 non-null  float64
 2   Failure Part Series              375364 non-null  object
 3   tfidf_work_sum                   375364 non-null  float64
 4   tfidf_diagnosis_sum              375364 non-null  float64
 5   tfidf_failure_part_descrip_sum   375364 non-null  float64
 6   work_performed_sentiment         375364 non-null  float64
 7   diagnosis_sentiment              375364 non-null  float64
 8   Failure Description              375364 non-null  object
 9   Number of Failure Parts          375364 non-null  int64
 10  Number of Replacement Parts      375364 non-null  int64
 11  Part Quantity                    375364 non-null  int64
 12  Part Extended Price              375364 non-null  float64
 13  Paid Labor Hours                 375364 non-null  float64
 14  Total Failure Cost               375364 non-null  float64
 15  Model Number                     375348 non-null  object
 16  Warranty Item Description        375364 non-null  object
 17  Serial Number                    374033 non-null  object
 18  Engine Model                     333224 non-null  object
 19  Transmission Model               277260 non-null  object
 20  Repair Dealer Number             368636 non-null  object
 21  Owner City                       305478 non-null  object
 22  Owner State                      305381 non-null  object
 23  Owner Zip                        305481 non-null  object
 24  Purchase Date                    375349 non-null  datetime64[ns]
 25  Failure Date                     375362 non-null  datetime64[ns]
 26  Repair Date                      375364 non-null  datetime64[ns]
 27  Hours Used                       375364 non-null  float64
 28  Posted Calendar Month Name Abbr  375364 non-null  object
 29  Total Claim Dollars              375364 non-null  float64
 30  Days of Usage                    375349 non-null  float64
 31  Failure Season                   305381 non-null  object
dtypes: datetime64[ns](3), float64(12), int64(4), object(13)
memory usage: 91.6+ MB

In [ ]:
# prompt: merged_claim_failure_replacement_df to local download

from google.colab import files
merged_claim_failure_replacement_df.to_csv('merged_claim_failure_replacement_df.csv', encoding = 'utf-8-sig')
files.download('merged_claim_failure_replacement_df.csv')